"""
report.py — daily decision report, written as markdown into the repo.

Renders in the GitHub mobile app, so it's readable anywhere with no hosting.
Run after ingest.py parse.

    python src/report.py

FIVE TABLES, one currency. λ — points of XI index per million euros — is
measured once per run by ffcore.bid.frontier() and printed in the header, and
every call below reads it:

    1. Field these eleven          your marks, then who on the slate improves them
    2. Buy today                   pts/M against the hurdle
    3. What you give up            the ladder λ was measured off
    4. Sell these                  the same rule with the sign flipped
    5. Exceptions                  fitness, and where the two XI sources split

Before λ, the buy rule was `gain > 0` — which bought any upgrade at any price —
and there was no sell rule at all, only a €/pt column with no threshold under
it. League-wide movers and recruitment live in reports/watchlist.md; how your
rivals behave lives in reports/rivals.md.

THE SLATE IS THE REPORT when you paste one into inputs/seen.txt. The app deals
a limited market, so a ranked list of everyone unowned is mostly players you
cannot buy. sec_slate() answers the only live question — of the players on
offer right now, which improve my XI, what should I bid, and who else wants
them — using ffcore.bid: the XI index gained by owning him, and the floor plus
the premium this league has actually paid over it. How many purchases went at
the floor is counted from the ledger on every run rather than stated here,
because the sentence that stated it went stale inside a fortnight (issue #23).

SCORING lives in ffcore/score.py now, shared with rivals.py so that your
squad and theirs are ranked by the same arithmetic — one builder, build(), so
the two reports cannot drift apart:

    score = shrunk points-per-match  x  fixture  x  P(start)

It is a RANKING INDEX, not a points forecast, and it cannot know four
things — all flagged in the report rather than hidden: promoted-side players
carry an assumed baseline, absence from the probable-XI page is not the same
as a blank percentage there, the fixture band is a guess nothing has graded
yet, and none of it has been checked against reality. Every snapshot appends the
whole squad, XI and bench, with the inputs that produced each score, to
data/decisions/squad_log.csv, and the λ every verdict was judged against to
data/decisions/lambda_log.csv, so that once jornadas exist you can ask what the
ranking cost you and whether the hurdle was set anywhere near right.

MIGRATED onto ffcore. Four things changed in substance:

  * fold(), num(), eur(), read_csv(), latest_only(), parse_stamp() and
    input_path() are gone — they were local copies. norm() in particular
    now matches the rest of the repo, so a name with an apostrophe or an
    initial joins the same way here as it does in squads.py.
  * The scorer is imported, not defined. Tuning SHRINK_K used to require
    editing two files that could silently disagree.
  * Cash comes from ffcore.league, which also reads rival balances and
    understands a time-of-day on the anchor. The old regex read the first
    number in the file and assumed midnight.
  * Your squad comes from the ledger via ffcore.league. inputs/squad.txt is
    still generated by squads.py and still works as a fallback, but it is no
    longer the source of truth.
"""

from __future__ import annotations

import os
import re
import sys
from collections import Counter
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# band_of(), drift_bands(), friction() and Friction.per_point() in ffcore/bid.py
# lost their only caller with the Cost/pt column: λ prices the same purchase
# against what the money would otherwise buy, which is the question Cost/pt was
# reaching for. They are left in place, not deleted — the drift term is the
# first thing to fold into the cost side of the ratio once a season of readings
# exists to fit it against.
from ffcore.bid import (Lambda, cost_of, deals,  # noqa: E402
                        demand_summary, frontier, premiums, ratio_of,
                        sell_test, suggest, verdict, xi_snapshots)
from ffcore.fixture import FIX_BAND, HOME_EDGE  # noqa: E402
from ffcore.league import League  # noqa: E402
from ffcore.second import (LEGEND, SECOND_SOURCE,  # noqa: E402
                           af_cell, second_cells)
from ffcore.score import (ABSENT_START, MAX_SLOT, NEUTRAL_START,  # noqa: E402
                          SLOT_LABEL, THIN, build, formations,
                          pick_xi, squad_pool)
from ffcore.tidy import (DECISIONS, REPORTS,  # noqa: E402
                         append_csv, input_path, latest_only, load_deadline,
                         load_market, load_lineups, read_csv, snapshot_stamp,
                         widen_csv, write_lines)
from seen import read_slate  # noqa: E402

HISTORY = REPORTS / "history"

STALE_HOURS = 14.0
MOVER_PCT = 1.0           # squad price moves worth printing

# Name particles that stay lowercase when title-casing a folded name.
# "le"/"el"/"la" are deliberately absent: Le Normand and El Hilali are far
# more common in this league than "de la Fuente" losing its lowercase.
PARTICLES = {"de", "del", "van", "von", "der", "den", "di", "da", "dos",
             "do", "y", "bin", "ibn", "ter"}

# Words dropped when a club name has to fit in a table cell.
TEAM_NOISE = {"real", "club", "cf", "fc", "ud", "cd", "rc", "rcd", "sd",
              "de", "deportivo"}

# A fixture is worth marking on a purchase row from this much swing up. Under
# it the draw is not the reason to buy or not buy.
FIX_MARK = 0.05

# data/decisions/squad_log.csv, in order. One list, so the migration and the
# write cannot disagree about what the file holds.
#
# The last six arrived with the fixture term and the current-season blend, and
# each is a SEPARATE column rather than folded into `score`: grading a forecast
# means attributing its error to one factor at a time. Was the eleven wrong
# about who starts, about the opponent, or about the player? A single number
# cannot answer that, and the two fixture constants are guesses waiting to be
# graded. Rows written before they existed keep an empty cell, which honestly
# says "not measured" rather than "average".
LOG_COLS = ["observed_at", "hours_to_lock", "formation", "index_total",
            "player", "pos", "slot", "start_pct", "start_source", "status",
            "assumed", "value", "score", "picked",
            "ppm", "fix", "opp", "home", "cur_pj", "flat",
            "fix_basis", "elo_gap"]

# How many unowned players per position λ is measured against. The app deals
# twelve random free agents a cycle, so the ladder is deliberately built from
# the whole unowned pool rather than today's slate — λ is what you WOULD buy if
# you could buy anything, which is what makes it a reservation rate. Trimmed
# per slot because only the best few in each can ever reach an eleven, and
# gain() is called once per candidate per rung.
LAMBDA_DEPTH = 8


def title_name(s: str) -> str:
    """market.csv hands us folded names; make them readable again.

    Accents survive (they're in the source string), particles stay lowercase,
    hyphenated parts are capitalised on both sides. Moves to ffcore/render.py
    when the other reports are migrated.
    """
    s = (s or "").strip()
    if not s or s != s.lower():
        return s  # already cased — leave it alone
    words = []
    for i, w in enumerate(s.split()):
        if i and w in PARTICLES:
            words.append(w)
        else:
            words.append("-".join(p[:1].upper() + p[1:] for p in w.split("-")))
    return " ".join(words)


def eur(v) -> str:
    if v is None:
        return "—"
    v = float(v)
    if abs(v) >= 1_000_000:
        return f"{v/1_000_000:.2f}M"
    if abs(v) >= 1_000:
        return f"{v/1_000:.0f}K"
    return f"{v:.0f}"


def short_team(name: str) -> str:
    """A team name that fits in a phone-width cell.

    Drops the noise words clubs share — `Real`, `Club`, `CF`, `UD` — and keeps
    the part that identifies them, so `Real Sociedad` and `Real Madrid` stay
    distinct while both get shorter. If stripping would leave nothing, the
    original survives: a cell that says `Real` for two different clubs is
    worse than a long one.
    """
    words = [w for w in (name or "").split()
             if w.lower() not in TEAM_NOISE]
    if not words:
        return (name or "").strip()
    kept = " ".join(words)
    # Still too wide for a cell: keep the FIRST word, not the last. Last would
    # turn Atlético Madrid into Madrid, which is another club.
    return words[0] if len(kept) > 11 and len(words) > 1 else kept


def vs_cell(p, star: bool = False) -> str:
    """Who he faces next, and whether that is a break. `—` = no fixture known.

    `star` is for the purchase rows: their xPts figure deliberately IGNORES
    the fixture (you own a player for months, not for one round), so the
    marker is how this round's draw shows up at all.
    """
    if not p.get("opp"):
        return "—"
    cell = "%s %s" % (short_team(p["opp"]), "H" if p.get("home") else "A")
    if star:
        fix = p.get("fix") or 1.0
        if fix >= 1.0 + FIX_MARK:
            cell += " ★"
        elif fix <= 1.0 - FIX_MARK:
            cell += " ↓"
    return cell


def fix_cell(p) -> str:
    """The fixture factor as a percentage swing. `=` is a median opponent,
    `—` means no fixture is known and the score was left unadjusted."""
    if not p.get("opp"):
        return "—"
    pct = ((p.get("fix") or 1.0) - 1.0) * 100
    return "=" if abs(pct) < 0.5 else "%+.0f%%" % pct


def candidates(sc, by_key, slate, owner) -> list[dict]:
    """Scored rows for everything on today's slate you do not already own.

    One list, two tables: question 1 asks what a purchase would add to the
    eleven, question 4 prices the same names. They were scored twice before,
    which is one refactor away from the two tables disagreeing.
    """
    out = []
    for k in slate[0]:
        if k in owner:
            continue
        rec = by_key.get(k)
        if not rec:
            continue
        cand = sc.score(rec).as_row()
        cand["name"] = title_name(cand["name"])
        out.append(cand)
    return out


def flat_gains(players, cands) -> dict[str, float]:
    """{candidate key: xPts/j the eleven gains by owning him, fixture-neutral}.

    The fielding question is one round, so `score` carries the opponent. The
    buying question is months, so this re-runs the same arithmetic on `flat`,
    which does not. A defender who only looks like an upgrade because his club
    happens to host the bottom side next Saturday is not an upgrade.
    """
    from ffcore.bid import gain

    neutral = squad_pool([{**p, "score": p["flat"]} for p in players])
    base = pick_xi(neutral)
    if base is None:
        return {}
    out = {}
    for c in cands:
        g = gain(neutral, {**c, "score": c["flat"]}, base[0])
        if g is not None:
            out[c["key"]] = g
    return out


# ---------------------------------------------------------------------------
# λ, the one number
#
# Every judgement in this report — field, buy, hold, sell — is now priced in
# the same unit: XI index points per million euros. λ is the going rate for
# cash, measured by ffcore.bid.frontier() rather than configured, and it is
# measured FIXTURE-NEUTRAL for the same reason gains are: you own a player for
# months, not for one round.
# ---------------------------------------------------------------------------


def neutral_view(players) -> tuple[dict, float | None]:
    """(pool, total) with the fixture taken back out. The buying scale."""
    pool = squad_pool([{**p, "score": p["flat"]} for p in players])
    best = pick_xi(pool)
    return pool, (best[0] if best else None)


def unowned(sc, by_key, owner, depth: int = LAMBDA_DEPTH) -> list[dict]:
    """The best few unowned players per position, scored fixture-neutral.

    Not today's slate: the slate is what you can buy in the next minute, and λ
    has to be what the money is worth over the season. Everything the market
    prices and nobody in the league holds is a candidate; only the top `depth`
    of each position can reach an eleven, so the rest are dropped before the
    greedy walk rather than during it.
    """
    rows: dict[str, list[dict]] = {}
    for k, rec in by_key.items():
        if k in owner:
            continue
        c = sc.score(rec).as_row()
        if not c["slot"]:
            continue
        c["name"] = title_name(c["name"])
        c["score"] = c["flat"]
        rows.setdefault(c["slot"], []).append(c)
    out = []
    for v in rows.values():
        v.sort(key=lambda p: p["score"], reverse=True)
        out += v[:depth]
    return out


def lambda_now(players, pool_flat, total_flat, cands, cash, prem) -> Lambda:
    """The going rate for your cash, or a Lambda that says why there isn't one.

    Never a zero: `rate=None` means λ cannot judge today, and every verdict
    that reads it falls back to the older question and says so.
    """
    if total_flat is None:
        return Lambda(None, [], 0.0, 0.0, "no legal XI to price against")
    return frontier(pool_flat, total_flat, cands, cash, prem)


def fix_basis_label(players) -> str:
    """What ranked the opponents, said out loud in the notes.

    One label for the whole board, because ffcore.fixture refuses a mixture:
    Club Elo covers every team or none of them.
    """
    kinds = {p.get("fix_basis") for p in players if p.get("opp")}
    if "elo" in kinds:
        return "Club Elo rating"
    if "value" in kinds:
        return ("summed squad value — Club Elo did not cover the league, so "
                "the wallet is standing in for the pitch")
    return "nothing: no fixture is known for anyone in your squad"


def sec_ladder(lam: Lambda, buffer: float) -> list[str]:
    """## 3. What you give up by spending now

    The ladder λ was measured off. This is the section that makes the hurdle
    arguable instead of magic: if the rungs are players you will never be
    dealt, λ is too high and you can see that here rather than infer it.
    """
    out = ["## 3. What you give up by spending now", ""]
    if lam.rate is None:
        return out + ["_No rate today — %s. Every verdict above falls back to "
                      "'does he improve the eleven', which is a weaker "
                      "question and is marked as such._" % lam.why, ""]

    out += ["**%s, hurdle %.2f.** Spending a million here means not spending "
            "it on these, best rate first — %s."
            % (lam.label(), lam.hurdle(buffer), lam.why), "",
            "| | Player | Slot | Cost | ΔxPts/j | pts/M |",
            "|---|---|---|--:|--:|--:|"]
    for i, r in enumerate(lam.ladder, 1):
        mark = " ←λ" if i == len(lam.ladder) else ""
        out.append("| %d%s | %s | %s | %s | %+.1f | %.2f |"
                   % (i, mark, r.name, r.slot, eur(r.cost), r.gain, r.ratio))
    out += ["",
            "_The last rung IS λ: it is the worst rate your cash could still "
            "buy, so anything worse than it is worse than doing nothing. Each "
            "gain is recomputed after the purchase above it, because two "
            "players who upgrade the same slot do not both upgrade it. Costs "
            "are the floor plus this league's median premium. Nobody in this "
            "table is necessarily on offer today — that is the point, and it "
            "is why λ reads as 'do not accept worse than this' rather than as "
            "a shopping list. The one haircut on it is `lambda_buffer` in "
            "`inputs/league.ini` (%.0f%%)._" % (buffer * 100), ""]
    return out


def log_lambda(observed, lam: Lambda, buffer: float) -> None:
    """One row per snapshot: the rate every verdict that day was judged against.

    Without this the rule is ungradeable. If the season's realised ratios sit
    above the λ printed at the time, λ was too low and the buffer was covering
    for it — a question this file can answer and a report cannot.
    """
    path = DECISIONS / "lambda_log.csv"
    cols = ["observed_at", "rate", "buffer", "hurdle", "cash", "spent",
            "rungs", "best_rate", "why"]
    widen_csv(path, cols)
    if observed in {r.get("observed_at") for r in read_csv(path)}:
        return
    hurdle = lam.hurdle(buffer)
    append_csv(path, [{
        "observed_at": observed,
        "rate": "" if lam.rate is None else f"{lam.rate:.4f}",
        "buffer": f"{buffer:.3f}",
        "hurdle": "" if hurdle is None else f"{hurdle:.4f}",
        "cash": f"{lam.cash:.0f}", "spent": f"{lam.spent:.0f}",
        "rungs": len(lam.ladder),
        "best_rate": ("" if not lam.ladder
                      else f"{lam.ladder[0].ratio:.4f}"),
        "why": lam.why,
    }], cols)


def as_fielded(players):
    """(total, xi, bench, illegal, warnings) for the XI you have MARKED.

    Reads inputs/lineup.txt — the checklist squads.py regenerates — so the
    report can say what your actual eleven is worth, not only what the best
    one would be. Returns None when there is no checklist to read: the
    comparison is skipped, never faked from the recommendation.

    `illegal` is the shape when the marks do not make a legal eleven, which
    is worth flagging louder than a suboptimal one — the app will fill the
    gap for you, and not with your choice.
    """
    from ffcore.text import norm
    from xi import bench_from_checklist, read_checklist

    path = input_path("lineup.txt")
    if not path.exists():
        return None
    entries = read_checklist(path.read_text(encoding="utf-8"))
    if not entries:
        return None

    names = [p["name"] for p in players]
    bench_keys, warnings = bench_from_checklist(names, entries)
    benched = {norm(b) for b in bench_keys}
    xi = [p for p in players if norm(p["name"]) not in benched]
    bench = [p for p in players if norm(p["name"]) in benched]

    counts = Counter(p["slot"] for p in xi if p["slot"])
    shape = (counts.get("DEF", 0), counts.get("MED", 0), counts.get("DEL", 0))
    illegal = None
    if len(xi) != 11 or counts.get("POR", 0) != 1 or shape not in set(
            formations()):
        illegal = "%d players, %d-%d-%d" % ((len(xi),) + shape)
    return sum(p["score"] for p in xi), xi, bench, illegal, warnings


def swaps(fielded_xi, best_xi):
    """[(out, in)] — who to bench for whom, paired within a position.

    Only same-slot pairs are offered. A cross-slot difference is a change of
    formation, not a substitution, and printing it as one would suggest an
    illegal move.
    """
    from ffcore.text import norm

    best_keys = {norm(p["name"]) for p in best_xi}
    out_ = [p for p in fielded_xi if norm(p["name"]) not in best_keys]
    have = {norm(p["name"]) for p in fielded_xi}
    in_ = [p for p in best_xi if norm(p["name"]) not in have]
    pairs = []
    for o in sorted(out_, key=lambda p: p["score"]):
        cand = [i for i in in_ if i["slot"] == o["slot"]]
        if cand:
            best_in = max(cand, key=lambda p: p["score"])
            in_.remove(best_in)
            pairs.append((o, best_in))
    return pairs


def load_squad_file() -> list[str]:
    """inputs/squad.txt — fallback only. The ledger is the source of truth."""
    path = input_path("squad.txt")
    if not path.exists():
        return []
    return [ln.strip() for ln in path.read_text(encoding="utf-8").splitlines()
            if ln.strip() and not ln.strip().startswith("#")]


def squad_names(lg) -> tuple[list[str], str]:
    """Your roster, and where it came from."""
    if lg is not None:
        mine = lg.managers.get(lg.cfg.me)
        if mine and mine.players:
            by_key = lg.market.latest() if lg.market else {}
            return ([by_key.get(k, {}).get("name", k) for k in mine.players],
                    "ledger")
    return load_squad_file(), "squad.txt"


def rival_ceiling(lg) -> float | None:
    """Largest bid any rival could still make, or None if any cash is unknown.

    An unknown balance is not a zero. Returning None where one rival's cash
    cannot be reconstructed is what stops suggest() telling you to bid the
    floor against someone who can outspend you.
    """
    bids = [m.max_bid for m in lg if m.handle != lg.cfg.me]
    if not bids or any(b is None for b in bids):
        return None
    return max(bids)


def sec_slate(lg, by_key, cands, pool, gains, slate, prem, cash_value,
              rival_max, snaps, sell_prem=None,
              second=None, lam=None, buffer=0.0) -> tuple[list[str], int, int]:
    """Today's slate, priced in λ. The section that answers 'what do I do now'.

    Everything else in this report describes a position; this one is a list of
    purchases you can make in the next few minutes. ΔxPts/j is the change in
    the ranking index from owning him and re-picking the formation — frequently
    negative for a player the watchlist ranks highly, because your own eleven is
    the benchmark — and dividing it by what he costs gives the only number the
    verdict reads.

    `gains` is flat_gains(): fixture-neutral, the same arithmetic λ was
    measured with. There used to be a second gain computed here off the
    fielding scale, so question 1 and question 4 could print two different
    numbers for the same signing.
    """
    on_offer, unresolved, ambiguous, auto = slate
    out: list[str] = []

    owned = {k: lg.owner[k] for k in on_offer if k in lg.owner}

    rows = []
    for cand in cands:
        g = gains.get(cand["key"])
        adv = suggest(cand["value"], prem, cash_value, rival_max)
        # How far below the thin threshold you are in HIS position. This is
        # what turns a negative-gain forward into cover rather than a pass.
        slot = cand.get("slot")
        short_by = (max(0, THIN[slot] - len(pool.get(slot, [])))
                    if slot in THIN else 0)
        cost = cost_of(cand["value"], prem)
        ratio = ratio_of(g, cost)
        rows.append((cand, g, adv, short_by, cost, ratio))

    # Best RATE first, not best gain: the question is what the money buys, and
    # a two-point upgrade for twelve million is a worse purchase than a
    # one-point upgrade for two. Cover sorts to the top when you cannot field a
    # legal XI without it; a player who cannot start sorts last whatever his
    # score, because the question here is what he adds to YOUR eleven.
    rows.sort(key=lambda r: (-r[3] if r[1] is not None and r[1] <= 0 else 0,
                             r[1] is None, -(r[5] if r[5] is not None
                                             else -1e9)))
    hurdle = lam.hurdle(buffer) if lam is not None else None
    better = sum(1 for r in rows if hurdle is not None and r[5] is not None
                 and r[5] > hurdle) if hurdle is not None else sum(
                     1 for r in rows if r[1] is not None and r[1] > 0)
    covers = sum(1 for _, g, a, sb, _, _ in rows
                 if sb > 0 and a.low is not None and g is not None)

    out += ["## 2. Buy today", "",
            "**%d on offer, %d beat the going rate for cash%s.**"
            % (len(rows), better,
               ", %d cover a position you are short in" % covers
               if covers else ""), ""]
    if not rows:
        out += ["_Every name you pasted is either already owned or missing "
                "from the market data._", ""]
    else:
        out += ["| Player | Pos | Bid | ΔxPts/j | pts/M | vs λ | "
                "Competition | Verdict |",
                "|---|---|--:|--:|--:|--:|---|---|"]
        for cand, g, adv, short_by, cost, ratio in rows:
            band = ("—" if adv.low is None
                    else eur(adv.low) if abs(adv.high - adv.low) < 1_000
                    else "%s–%s" % (eur(adv.low), eur(adv.high)))
            vs = ("—" if ratio is None or not hurdle
                  else "%.2f×" % (ratio / hurdle))
            out.append(
                "| %s | %s | %s | %s | %s | %s | %s | %s |"
                % (cand["name"], (cand["pos"] or "—")[:3], band,
                   "—" if g is None else "%+.1f" % g,
                   "—" if ratio is None else "%+.2f" % ratio,
                   vs, demand_summary(cand, lg, snaps),
                   verdict(g, adv, short_by, ratio, lam, buffer)))
        out += ["",
                "**pts/M** is ΔxPts/j divided by what winning him is expected "
                "to cost — the one currency, and the only number the verdict "
                "reads. **vs λ** is that rate over the hurdle: above 1.00× the "
                "money is better spent here than on the ladder in question 3, "
                "below it you are paying more than the going rate. A purchase "
                "is closer to a loan than a spend — the value comes back when "
                "you sell, give or take %s, which on a large player is bigger "
                "than the premium and the drift put together. That swing is a "
                "coin flip, so a row inside a few percent of 1.00× is not a "
                "decision."
                % ("%.0f%%" % sell_prem.swing() if sell_prem
                   else "about a tenth"),
                "",
                LEGEND, "",
                "Competition is demand, not roster counts: the rivals whose "
                "XI actually improves with him, strongest threat first — "
                "`?` cash unknown (treat as live), `(n broke)` want him but "
                "cannot pay the floor. The full manager-by-manager matrix is "
                "in `reports/rivals.md`.", "",
                "Bid is the floor plus what this league has actually paid over "
                "it: %s.%s A dozen deals is not a distribution — the range is "
                "what has happened, not a chance of winning, and every one of "
                "them is a bid that won."
                % (prem.label() if prem else
                   "no priced purchase yet, so these are floors",
                   ("" if not prem else
                    " %d of those %d went at the floor itself, so the minimum "
                    "is not a number known to lose." % (prem.at_floor, prem.n)
                    if prem.at_floor else
                    " None of those %d went at the floor." % prem.n)), ""]
        # EVERY BID IS PRICED AS IF IT WERE THE ONLY ONE. Each row asks "is
        # this better than the going rate", and several rows can answer yes to
        # more money than you hold — the app settles them all at once, so the
        # arithmetic has to be stated rather than left to the reader.
        bidding = [(c, a) for c, g, a, sb, _, r in rows
                   if a.low is not None and hurdle is not None
                   and r is not None and r > hurdle]
        wanted = sum(a.low for _, a in bidding)
        if len(bidding) > 1 and cash_value is not None and wanted > cash_value:
            out += ["**⚠ %d bids at %s is more than the %s you hold.** Each row "
                    "above is priced as though it were your only purchase, and "
                    "the app settles them together — take them best rate "
                    "first: %s."
                    % (len(bidding), eur(wanted), eur(cash_value),
                       ", ".join(c["name"] for c, _ in bidding)), ""]
        if rival_max is None:
            out += ["_At least one rival's cash is an estimate, so no bid here "
                    "assumes you are unopposed._", ""]
        if cash_value is None:
            out += ["_Your own balance is not a recorded number, so no bid is "
                    "capped by what you actually have. Put it in "
                    "`inputs/cash.txt`._", ""]

    if owned:
        out += ["Already owned, so not a purchase: %s." % ", ".join(
            "%s (%s)" % (by_key.get(k, {}).get("name", k),
                         "you" if h == lg.cfg.me else h)
            for k, h in sorted(owned.items())), ""]

    if auto:
        # Printed, not hidden: this is the one place the repo guesses between
        # candidates, and it guesses off a ledger you maintain by hand. If a
        # line here names the wrong player, the fix is a missing row in
        # transactions.csv (issue #26).
        out += ["**Placed by ownership, not by the name.** The app deals free "
                "agents, so a candidate somebody already holds is not the one "
                "on offer — check these if one looks wrong:", ""]
        out += ["- " + a for a in auto] + [""]

    if unresolved or ambiguous:
        # A heading, not bold text, so digest.py prints it once instead of
        # repeating the watchlist's copy of the same list.
        out += ["## Names I could not place", "",
                "OCR mangled these past matching, so they are missing from "
                "the table above — re-read them off the app if one matters.",
                ""]
        out += ["- **%s** — no match" % u for u in unresolved]
        out += ["- **%s** — could be %s" % (raw, ", ".join(c))
                for raw, c in ambiguous]
        out.append("")
    return out, len(rows), better


def log_squad(observed, players, chosen, formation, total, deadline,
              obs_dt) -> None:
    """Append-only record of every recommendation, for scoring later.

    One row per player per snapshot — long format, so a scorer can group by
    snapshot without parsing packed strings. hours_to_lock is stored rather
    than an at-lock flag, because a run cannot know whether a later snapshot
    will still beat the deadline: the scorer picks, per jornada, the row with
    the smallest non-negative value.

    The bench is logged too. Without it "what did the ranking cost me" is
    unanswerable after the fact, and that is the whole point of keeping this.
    """
    path = DECISIONS / "squad_log.csv"
    # Before the dedup check, not after: a run that has nothing new to log
    # still has to carry the migration, or the columns would only appear on
    # whichever run happens to see a fresh snapshot first.
    widen_csv(path, LOG_COLS)
    if observed in {r.get("observed_at") for r in read_csv(path)}:
        return
    htl = ""
    if deadline and obs_dt:
        htl = f"{(deadline - obs_dt).total_seconds() / 3600:.1f}"
    rows = []
    for p in players:
        src = ("read" if p["pct"] is not None
               else "listed_blank" if p["on_page"] else "absent")
        rows.append({
            "observed_at": observed, "hours_to_lock": htl,
            "formation": "-".join(str(x) for x in formation),
            "index_total": f"{total:.2f}",
            "player": p["name"], "pos": p["pos"], "slot": p["slot"],
            "start_pct": "" if p["pct"] is None else f"{p['pct']:.0f}",
            "start_source": src, "status": p["status"] or "ok",
            "assumed": int(bool(p["assumed"])),
            "value": f"{p['value']:.0f}", "score": f"{p['score']:.3f}",
            "picked": int(id(p) in chosen),
            "ppm": f"{p['ppm']:.3f}", "fix": f"{p['fix']:.3f}",
            "opp": p["opp"], "home": int(bool(p["home"])) if p["opp"] else "",
            "cur_pj": f"{p['cur_pj']:.0f}", "flat": f"{p['flat']:.3f}",
            # Which scale ranked his opponent, and by how much. Empty rather
            # than zero when there was no Elo: a missing rating is not a
            # level match-up.
            "fix_basis": p.get("fix_basis") or "none",
            "elo_gap": ("" if p.get("elo_gap") is None
                        else f"{p['elo_gap']:.1f}"),
        })
    append_csv(path, rows, LOG_COLS)


# ---------------------------------------------------------------------------
# The five tables
#
# Field these eleven, buy today, what you give up by spending now, sell these,
# and the exceptions. In that order, because that is the order the decisions
# get made in, and every one of them is priced in the same unit — λ, points of
# index per million euros. A section that cannot price its call in λ says so.
# Everything else — premium curves, drift, full rosters, deal history,
# methodology — is reference and lives below the fold or in its own file.
#
# Question 1 leads with WHAT YOU ARE FIELDING, not with what the model would
# field. The marks in inputs/lineup.txt are a fact; the recommendation is
# advice, and printing advice as though it were the team is how the old report
# managed to show two different benches under the same word.
# ---------------------------------------------------------------------------

STATE_LABEL = {
    "injured": "🔴 injured",
    "suspended": "🔴 suspended",
    "unavailable": "🔴 unavailable",
    "doubt": "🟡 doubt",
    "ok": "fit",
}


def sec_eleven(marked, best, players, second=None, buys=None) -> list[str]:
    """## 1. Field these eleven"""
    out = ["## 1. Field these eleven", ""]

    if not players:
        return out + ["_No roster. Check `inputs/rosters_initial.txt` and "
                      "`inputs/transactions.csv`._", ""]
    if marked is None:
        return out + ["_No marks to read. `inputs/lineup.txt` is missing or "
                      "empty — run `squads.py`, then tick the eleven you are "
                      "fielding._", ""]

    mtot, mxi, mbench, illegal, mwarn = marked
    counts = Counter(p["slot"] for p in mxi if p["slot"])
    shape = "%d-%d-%d" % (counts.get("DEF", 0), counts.get("MED", 0),
                          counts.get("DEL", 0))

    if illegal:
        out += [f"**⚠ Not a legal eleven — {illegal}.** The app will fill the "
                "gaps for you, and not with your choice. Fix "
                "`inputs/lineup.txt`.", ""]
    else:
        # NOT "≈N points": the index is an uncalibrated ranking number, and
        # printing it with a points unit on it invited exactly the comparison
        # it cannot support — against a rival's realised score, against last
        # jornada. It is only ever worth reading as a difference.
        out += [f"**Your XI: {shape} · index {mtot:.1f}** (a ranking number, "
                "not a points forecast — only differences mean anything)", ""]

    # One table for both halves of the same decision: the eleven you are
    # fielding, then the players on today's slate who would improve it. They
    # used to be four sections apart, which made "would this signing get into
    # my team" a question you answered by scrolling.
    #
    # Each factor gets its own column instead of one blended number. Only
    # pts/m is shared between the two sources — points per match is a record,
    # and both sites read the same one — so blending is only ever tempting for
    # the two start columns, and that is exactly where it would hide a
    # disagreement worth seeing. State has moved to question 2.
    cells = second or {}
    out += ["| | Marked XI | vs | pts/m | Fix | FF | AF | xPts/j |",
            "|---|---|---|--:|--:|--:|--:|--:|"]
    for slot in ("POR", "DEF", "MED", "DEL"):
        for p in [x for x in mxi if x["slot"] == slot]:
            flag = " ⚠" if (p["status"] or "ok") != "ok" else ""
            out.append(f"| {slot} | {p['name']}{flag} | {vs_cell(p)} | "
                       f"{ppm_cell(p)} | {fix_cell(p)} | {pct_cell(p)} | "
                       f"{af_cell(cells.get(p['key']))} | "
                       f"{p['score']:.1f} |")

    # Purchase rows, in the same columns and the same units, so the comparison
    # is a glance down one column rather than arithmetic between two tables.
    up = sorted(((c, g) for c, g in (buys or []) if g > 0.05),
                key=lambda t: -t[1])
    passed = len(buys or []) - len(up)
    for cand, g in up:
        out.append(f"| +{cand['slot']} | _{cand['name']}_ | "
                   f"{vs_cell(cand, star=True)} | {ppm_cell(cand)} | "
                   f"{fix_cell(cand)} | {pct_cell(cand)} | "
                   f"{af_cell(cells.get(cand['key']))} | **{g:+.1f}** |")

    out += ["",
            "_**pts/m** is points per match, last season shrunk toward the "
            "average and blended with this season as it accrues. `~` means no "
            "record at all, so the baseline is assumed. **Fix** is how much "
            "the next opponent moves it — `=` a median team, `—` no fixture "
            "known. **FF** is futbolfantasy's start percentage, **AF** is "
            "analiticafantasy's — `titular` there is a named starter with no "
            "number attached, `?` is listed without either, `—` is not listed "
            "at all. They are separate columns because neither has been "
            "checked against a played jornada yet, so there is no weight to "
            "blend them by, and a disagreement is worth more than an average. "
            "**xPts/j** = pts/m × Fix × FF, and uses FF only. "
            "`⚠` on a name means question 5 has something on him._", ""]
    if up:
        out += ["_The `+SLOT` rows are today's slate: **xPts/j is the change "
                "to the whole eleven** if you sign him and re-pick the shape, "
                "not his own score, and it leaves the fixture OUT — you own a "
                "player for months, not for one round. `★` next to the "
                "opponent means this round's draw happens to be kind, `↓` that "
                "it is not; neither is in the number. What he would cost, and "
                "whether that is a good rate, is question 2._"
                + ("" if not passed else
                   " _%d other%s on the slate would not improve this eleven, "
                   "so they are priced there and not here._"
                   % (passed, "" if passed == 1 else "s")), ""]

    if best is None:
        return out + ["_No legal XI available from this squad, so there is "
                      "nothing to compare against._", ""]

    btot, (d, m, f), bxi = best
    gap = btot - mtot
    if gap <= 0.05:
        out += [f"**Nothing to change.** The model's best legal XI is the same "
                f"eleven ({d}-{m}-{f}, index {btot:.1f}).", ""]
        return out

    pairs = swaps(mxi, bxi)
    out += [f"**The model's eleven is {gap:.1f} better** (index {btot:.1f}, "
            f"shape {d}-{m}-{f}).", ""]
    if not pairs:
        out += ["_The difference is a change of formation, not a substitution, "
                "so there is no like-for-like swap to offer._", ""]
        return out

    out += ["| Bench this | For this | Worth |", "|---|---|--:|"]
    for o, i in pairs:
        out.append(f"| {o['name']} ({o['score']:.1f}) | "
                   f"{i['name']} ({i['score']:.1f}) | "
                   f"{i['score'] - o['score']:+.1f} |")
    out += ["", "_Swaps are same-position only: a cross-slot difference is a "
                "change of formation, not a substitution. Your own marks are "
                "the row above — this table is advice._", ""]

    for w in mwarn:
        out.append(f"- ⚠ {w}")
    if mwarn:
        out.append("")
    return out


def sec_fitness(players) -> list[str]:
    """### Fitness — who is not available

    Every squad member gets a row, including the ones nothing is known about.
    Silence and fitness must not look the same: an empty section used to be
    indistinguishable from a clean bill of health, and for the whole life of
    this repo that is exactly what it was — the status column was dead.

    A SUBSECTION now, not question 2. Fitness and the start splits do not price
    anything in λ — they are the two ways the numbers above can be wrong about
    a player, which makes them exceptions to check, not decisions to take.
    """
    out = ["### Fitness", ""]
    if not players:
        return out + ["_No roster to check._", ""]

    flagged = [p for p in players if p["status"] and p["status"] != "ok"]
    nodata = [p for p in players if not p["on_page"]]
    fit = [p for p in players
           if p["on_page"] and (not p["status"] or p["status"] == "ok")]

    if flagged:
        out += [f"**{len(flagged)} of {len(players)} flagged.**", ""]
    else:
        out += [f"**Nobody in your squad is flagged.** All {len(fit)} players "
                "with an entry on their team page read as available.", ""]

    # Rows for what is wrong or unknown; one line for what is fine. Every
    # player is still accounted for — the guarantee above is that silence and
    # fitness must not look the same, and they do not: a no-data player keeps
    # his own row and the fit ones are named, not merely counted. What is gone
    # is fifteen table rows reading "fit | listed, no flag" on a phone screen.
    if flagged or nodata:
        out += ["| Player | State | What the page says |", "|---|---|---|"]
        order = {"injured": 0, "suspended": 1, "unavailable": 2, "doubt": 3}
        for p in sorted(flagged, key=lambda x: order.get(x["status"], 9)):
            out.append(f"| {p['name']} | "
                       f"{STATE_LABEL.get(p['status'], p['status'])}"
                       f" | {p['note'] or '—'} |")
        for p in sorted(nodata, key=lambda x: x["name"]):
            out.append(f"| {p['name']} | ⚪ no data | not listed on his team "
                       "page — unknown, not fit |")
        out.append("")
    if fit:
        out += [f"_Listed with no flag ({len(fit)}): "
                + ", ".join(p["name"] for p in sorted(fit,
                                                      key=lambda x: x["name"]))
                + "._", ""]

    if nodata:
        out += [f"_{len(nodata)} player(s) have no entry on their team page. "
                "That is an absence of evidence, not evidence of fitness — "
                "check them in the app before the lock._", ""]
    out += ["_Read from the 'Estado físico', 'Sancionados' and 'No "
            "disponibles' blocks of each team page. A knock the site still "
            "lists as available (`Tocado`) is folded into doubt._", ""]
    return out


def sec_sell(players, pool, marked, chosen, pool_flat, total_flat,
             lam: Lambda | None, buffer: float, app_prem=None) -> list[str]:
    """## 4. Sell these

    THE BENCH, PRICED. It used to be a sell shortlist ordered by €/pt — value
    over expected points, which is a number with no threshold attached, so it
    ranked your spare players without ever saying whether to sell one. λ
    supplies the threshold: cash buys points at the going rate, so hold a
    player only while what he adds to the eleven beats what his sale proceeds
    would buy. That is the buy rule with the sign flipped, which is why there
    is no second setting to tune.

    Priced on the fixture-neutral scale, like every other λ judgement: you sell
    a player for months, not for one round.
    """
    out = ["## 4. Sell these", ""]
    if not players:
        return out + ["_No roster to price._", ""]

    spare = (marked[2] if marked else
             [p for p in players if id(p) not in chosen])
    source = ("as you have marked them" if marked
              else "the model's spare players — no checklist to read")
    if not spare:
        return out + ["_Nobody is out of your eleven (%s), so there is nothing "
                      "here to sell._" % source, ""]

    # Keyed by name because the neutral pool holds copies, and marginal() has
    # to be asked about the player as the pool knows him.
    flat_by_name = {p["name"]: p for v in pool_flat.values() for p in v}
    rank = {id(p): i for v in pool.values() for i, p in enumerate(v)}
    hurdle = lam.hurdle(buffer) if lam is not None else None

    rows = []
    for p in spare:
        sale = (sell_test(pool_flat, flat_by_name.get(p["name"], p),
                          total_flat, lam, app_prem, buffer)
                if total_flat is not None else None)
        rate = (None if sale is None or sale.loss is None or not sale.cash
                else sale.loss / (sale.cash / 1e6))
        if p["status"] in ("injured", "suspended", "unavailable"):
            why = p["status"]
        elif p["status"] == "doubt":
            why = "doubtful"
        elif sale is not None and sale.loss is None:
            why = "the only one who can fill his slot"
        elif p["slot"] and rank.get(id(p), 0) >= MAX_SLOT[p["slot"]]:
            nth = rank[id(p)] + 1
            sfx = ("th" if nth % 100 in (11, 12, 13)
                   else {1: "st", 2: "nd", 3: "rd"}.get(nth % 10, "th"))
            why = (f"{nth}{sfx} {p['slot']} — only "
                   f"{MAX_SLOT[p['slot']]} can ever play")
        elif p["delta_pct"] >= MOVER_PCT:
            why = "rising — sell into strength"
        elif p["pos"] == "entrenador":
            why = "coach slot"
        else:
            why = "outscored"
        rows.append((p, sale, rate, why))

    # Worst rate first: the man whose points cost you the most to keep is the
    # one to sell, and he sorts to the top whether or not the verdict says so.
    rows.sort(key=lambda t: (t[2] is None, t[2] if t[2] is not None else 0.0))

    out += ["| Player | Pos | Sale | Given up | pts/M | vs λ | Verdict | Why |",
            "|---|---|--:|--:|--:|--:|---|---|"]
    for p, sale, rate, why in rows:
        band = ("—" if sale is None
                else "%s–%s" % (eur(sale.lo), eur(sale.hi)))
        out.append(
            "| %s | %s | %s | %s | %s | %s | %s | %s |"
            % (p["name"], (p["pos"] or "—")[:3], band,
               "—" if sale is None or sale.loss is None
               else "%.1f" % sale.loss,
               "—" if rate is None else "%.2f" % rate,
               "—" if rate is None or not hurdle
               else "%.2f×" % (rate / hurdle),
               "hold" if sale is None else sale.verdict.split(" — ")[0],
               why))
    out += ["",
            "_**Given up** is what the eleven loses without him, after "
            "re-picking the shape — not his own score, and `—` means no legal "
            "XI survives his sale, which is a Keep at any price. **pts/M** is "
            "that loss over what the sale raises: the rate you are paying to "
            "keep him. **vs λ** puts it against the same hurdle question 2 "
            "uses, so **below 1.00× his points are dearer than the market's "
            "and the money is better elsewhere**. Two things this cannot see. "
            "Each sale is priced ON ITS OWN — sell two players out of the same "
            "position and the second one's Given up is no longer the number "
            "above, so re-read the thin-position warnings below the rule. And "
            "a name question 1 wants in your eleven can still be a Sell: "
            "fielding is one round, selling is the season, and the proceeds "
            "buy the ladder in question 3. %s Who is short in his position, "
            "and who can still afford you, is in `reports/rivals.md`._"
            % ("Selling to the app pays the value give or take %.0f%%: the %d "
               "priced sales in the ledger went %s, which is the band in the "
               "Sale column and is wide enough that a row near 1.00× is a coin "
               "flip." % (app_prem.swing(), app_prem.n, app_prem.label())
               if app_prem and app_prem.n >= 3 else
               "A sale lands above or below value depending on who bids."),
            ""]
    return out


def pct_cell(p) -> str:
    """Start percentage, marked when it is an assumption rather than a
    reading. `~` = listed with no figure, `!` = not on the page at all."""
    if p["pct"] is not None:
        return f"{p['pct']:.0f}%"
    return ("~" if p["on_page"] else "!") + \
        f"{NEUTRAL_START if p['on_page'] else ABSENT_START:.0f}%"


def ppm_cell(p) -> str:
    """Points per match. `~` marks a player with no top-flight record, whose
    baseline is assumed rather than earned."""
    return ("~" if p["assumed"] else "") + f"{p['ppm']:.1f}"


def disagrees(p, row, min_start: float) -> str:
    """Why the two sources conflict for this player, or ''.

    Only a conflict that would change the decision counts: one source putting
    him in the eleven while the other does not.
    """
    if not row:
        return ""
    likely = p["pct_used"] >= min_start
    named = (row.get("role") == "starter"
             or (row.get("start_pct") not in (None, "")
                 and float(row["start_pct"]) >= min_start))
    if likely and not named:
        return f"futbolfantasy {pct_cell(p)}, {SECOND_SOURCE} {af_cell(row)}"
    if named and not likely:
        return f"{SECOND_SOURCE} {af_cell(row)}, futbolfantasy {pct_cell(p)}"
    return ""


def sec_starting(marked, min_start, second=None,
                 unclear=None) -> list[str]:
    """### Starting — where the two sources disagree

    EXCEPTIONS ONLY. This used to print all fifteen players with a Reading
    column, and on a normal day fourteen of those rows read "published" — a
    column of the same word, pushing the one row that mattered off a phone
    screen. Every start figure is now in question 1's table, so what belongs
    here is only what question 1 cannot show: who is under the threshold, and
    where the two sources contradict each other.
    """
    out = ["### Starting", ""]
    if marked is None:
        return out + ["_No marks to read — see question 1._", ""]

    cells = second or {}
    _, mxi, mbench, _, _ = marked
    low = [p for p in mxi if p["pct_used"] < min_start]
    split = [(p, lab, why) for lab, group in (("XI", mxi), ("bench", mbench))
             for p in group
             for why in [disagrees(p, cells.get(p["key"]), min_start)] if why]

    if not low and not split and not unclear:
        out += [f"**Nothing to check.** Every marked player is at "
                f"{min_start:.0f}% or above on futbolfantasy, and "
                f"analiticafantasy does not contradict any of them.", ""]
    if low:
        out += [f"**{len(low)} of your marked XI are under {min_start:.0f}%:** "
                + ", ".join(f"{p['name']} ({pct_cell(p)})" for p in low)
                + ".", ""]
    if split:
        out += ["**The two sources disagree** — one of them has him in the "
                "eleven and the other does not. Neither has a track record "
                "here yet, so this is a prompt to open the app, not a verdict:",
                ""]
        out += ["| | Player | The split |", "|---|---|---|"]
        for p, lab, why in split:
            out.append(f"| {lab} | {p['name']} | {why} |")
        out.append("")
    if unclear:
        out += [f"_{len(unclear)} name(s) could not be matched to "
                f"analiticafantasy without guessing, so they carry no AF cell: "
                + "; ".join(f"**{n}** → {', '.join(c)}" for n, c in unclear)
                + ". A wrong player is worse than a blank one._", ""]

    out += ["_Both figures are editorial reads refreshed a few times a day, "
            "not live probabilities. `~` means listed with no figure "
            f"(assumed {NEUTRAL_START:.0f}%), `!` not on the page at all "
            f"(assumed {ABSENT_START:.0f}%). Threshold is `min_start` in "
            "`inputs/league.ini`._", ""]
    return out


def main() -> None:
    all_market = load_market()
    market = latest_only(all_market)
    xi_rows = latest_only(load_lineups())

    REPORTS.mkdir(exist_ok=True)
    HISTORY.mkdir(parents=True, exist_ok=True)

    if not market:
        write_lines(REPORTS / "latest.md", [
            "# Fantasy report", "",
            "No market data in `data/tidy/market.csv`. "
            "Did `ingest.py parse` run?"])
        print("no market data; wrote placeholder report")
        return

    try:
        lg = League.load()
    except SystemExit as exc:
        # rosters_initial.txt missing — fall back to squad.txt so a
        # half-configured repo still produces a report.
        print("league not loaded (%s); using squad.txt" % exc)
        lg = None

    # One builder, shared with rivals.py: the same points blend and the same
    # fixture board score your squad and theirs.
    shrink_k = lg.cfg.shrink_k if lg else 8.0
    sc, (hist_label, cur_label) = build(market, xi_rows,
                                        datetime.now(timezone.utc),
                                        shrink_k=shrink_k)

    observed = market[0]["observed_at"]
    obs_dt = snapshot_stamp(observed)
    now = datetime.now(timezone.utc)
    age_h = (now - obs_dt).total_seconds() / 3600 if obs_dt else None

    # --- build squad records ---------------------------------------------
    squad, squad_src = squad_names(lg)
    scored, missing = sc.score_squad(squad)
    players = []
    for s in scored:
        row = s.as_row()
        row["name"] = title_name(row["name"])
        players.append(row)
    squad_value = sum(p["value"] for p in players)

    pool = squad_pool(players)
    best = pick_xi(pool) if players else None
    chosen = {id(p) for p in best[2]} if best else set()

    # --- today's slate ----------------------------------------------------
    # Built before the header because the count belongs in the alerts: when a
    # slate has been pasted, it is the decision, and the rest of the report is
    # the position it is being made from.
    cash = lg[lg.cfg.me].cash if lg and lg.cfg.me in lg.managers else None
    cash_value = cash.value if cash and cash.confidence == "known" else None
    by_key = lg.market.latest() if lg and lg.market else {}
    slate = read_slate(by_key, lg.owner) if by_key else (set(), [], [], [])
    # Priced once: the buy side sizes a bid, and the sell side is what the app
    # pays you for a player, which the bench table needs whether or not a slate
    # was pasted.
    dl = deals(lg, lg.market) if lg and lg.market else []
    app_prem = premiums(dl, "sell")
    buy_prem = premiums(dl)
    # Scored once, read twice: question 1 asks what they add to the eleven,
    # question 2 asks what they cost.
    cands = candidates(sc, by_key, slate, lg.owner) if lg and by_key else []
    fg = flat_gains(players, cands) if cands and players else {}
    buys = [(c, fg[c["key"]]) for c in cands if c["key"] in fg]

    # --- λ, measured once and read by every verdict below -----------------
    # The buying scale: fixture-neutral, because you own a player for months.
    # Both sides of the market are priced against this one number, which is the
    # whole point of it — the old report had one rule for buying (`gain > 0`)
    # and no rule at all for selling.
    pool_flat, total_flat = neutral_view(players) if players else ({}, None)
    buffer = lg.cfg.lambda_buffer if lg else 0.25
    # A RECORDED balance, not an estimate: λ divides by it, and every verdict
    # in the report reads λ. An estimate would move every call in the file
    # without appearing in any of them, so a missing balance means no rate and
    # the fallbacks say so out loud.
    lam = lambda_now(players, pool_flat, total_flat,
                     unowned(sc, by_key, lg.owner) if lg and by_key else [],
                     cash_value, buy_prem)
    # The second opinion, joined once and printed in every table below.
    # Candidates are joined too, or their AF cell would always read `—` and
    # look like a source that has nothing on them.
    second, unclear = second_cells(
        [p["name"] for p in players]
        + [c["name"] for c in cands
           if c["key"] not in {p["key"] for p in players}])
    slate_lines, n_slate, n_better = [], 0, 0
    if any(slate):
        # The same snapshots rivals.py prints in its section 6, so the
        # Competition column and the matrix can never disagree.
        snaps = xi_snapshots(lg, sc, by_key)
        slate_lines, n_slate, n_better = sec_slate(
            lg, by_key, cands, pool, fg, slate,
            buy_prem, cash_value, rival_ceiling(lg), snaps,
            sell_prem=app_prem, second=second, lam=lam, buffer=buffer)

    # --- assemble ---------------------------------------------------------
    # FIVE TABLES, in the order the decisions get made: field, buy, what the
    # money would otherwise buy, sell, and the exceptions that would make any
    # of the three wrong. Everything below the rule is reference.
    marked = as_fielded(players) if players else None
    min_start = lg.cfg.min_start if lg else 60.0

    out: list[str] = [f"# Fantasy report — {observed}", ""]

    ctx = []
    # Derived from the next kickoff when fixtures have been scraped, so it
    # cannot go stale the way a typed date did. The source is printed: a
    # deadline you cannot trace is one you stop trusting.
    deadline, dl_src = load_deadline(with_source=True)
    if deadline:
        left = (deadline - now).total_seconds() / 3600
        if left < 0:
            ctx.append("**Deadline passed** — update `inputs/deadline.txt`")
        elif left < 48:
            ctx.append(f"**Locks in {left:.0f}h**"
                       + (" (next kickoff)" if dl_src == "fixtures" else ""))
        else:
            ctx.append(f"Locks in {left / 24:.0f} days")
    ctx.append(f"squad {eur(squad_value)}")
    if cash and cash.value is not None:
        ctx.append(f"cash {cash.label()}")
        ctx.append(f"total {eur(squad_value + cash.value)}")
    # λ in the header, once, because it is the number every table below is
    # measured in. Naming it here is what stops each section inventing its own
    # threshold, which is how the report ended up buying at `gain > 0` and
    # never selling at all.
    ctx.append(lam.label()
               + ("" if lam.rate is None
                  else " · buy over %.2f" % lam.hurdle(buffer)))
    out += [" · ".join(ctx), ""]

    out += sec_eleven(marked, best, players, second, buys)
    out += (slate_lines if slate_lines else
            ["## 2. Buy today", "",
             "_No slate pasted, so there is nothing you can bid on today that "
             "this report knows about. Paste today's market screenshot into "
             "the `seen` input to price it. Everyone unowned is ranked in "
             "`reports/watchlist.md`, and question 3 is what your cash is "
             "worth while you wait._", ""])
    out += sec_ladder(lam, buffer)
    out += sec_sell(players, pool, marked, chosen, pool_flat, total_flat,
                    lam, buffer, app_prem)
    out += ["## 5. Exceptions", "",
            "_The two ways every number above can be wrong about a player: he "
            "is not fit, or the two probable-XI sources do not agree that he "
            "plays. Neither prices anything, so neither is a decision — both "
            "are prompts to open the app._", ""]
    out += sec_fitness(players)
    out += sec_starting(marked, min_start, second, unclear)

    out += ["---", ""]
    if players and best:
        log_squad(observed, players, chosen, best[1], best[0], deadline,
                  obs_dt)
    log_lambda(observed, lam, buffer)

    # --- below the fold ---------------------------------------------------
    warnings: list[str] = []
    if age_h is not None and age_h > STALE_HOURS:
        warnings.append(f"**Data is {age_h:.0f}h old** — the ingest workflow "
                        "may have failed. Everything above is that snapshot.")
    if best:
        for k, n in THIN.items():
            have = len(pool.get(k, []))
            if have < n:
                warnings.append(f"**Only {have} {SLOT_LABEL[k]}"
                                f"{'s' if have != 1 else ''}** — one knock and "
                                "you can't field a legal XI.")
        guessed = [p["name"] for p in best[2] if p["assumed"]]
        if guessed:
            warnings.append(f"**{len(guessed)} unmodelled** "
                            f"({', '.join(guessed)}) — no LaLiga record, so "
                            "they carry an assumed baseline, not an earned "
                            "one.")
    if missing:
        warnings.append("**Not found in the market:** "
                        + ", ".join(f"`{m}`" for m in missing)
                        + " — check them with find_slug.py.")
    if cash and cash.value is not None and cash.confidence != "known":
        warnings.append("Cash is an estimate — record an observed balance in "
                        "`inputs/cash.txt`.")
    elif cash and cash.value is not None:
        last_tx = max((t.get("date") or "" for t in lg.txns), default="")
        anchor = re.search(r"\d{4}-\d{2}-\d{2}", cash.basis or "")
        if anchor and last_tx and last_tx[:10] > anchor.group(0):
            warnings.append(f"Balance last checked {anchor.group(0)}, but the "
                            f"ledger moved on {last_tx[:10]}. Re-check it.")
    elif not cash or cash.value is None:
        warnings.append("No cash figure — add `inputs/cash.txt`.")

    out += ["## Warnings", ""]
    out += ([f"- {w}" for w in warnings] if warnings
            else ["_Nothing flagged._"])
    out += ["", "_Compare squad value with the app; a mismatch means a name "
                f"matched the wrong player. Roster read from the "
                f"{squad_src}._", ""]

    # --- your movers ------------------------------------------------------
    movers = sorted((p for p in players if abs(p["delta_pct"]) >= MOVER_PCT),
                    key=lambda p: p["delta_pct"], reverse=True)
    out += [f"## Your movers (24h, over {MOVER_PCT:.0f}%)", ""]
    if not movers:
        out += ["_Nothing in your squad moved much._", ""]
    else:
        out += ["| Player | Value | 24h | % |", "|---|--:|--:|--:|"]
        for p in movers:
            out.append(f"| {p['name']} | {eur(p['value'])} | "
                       f"{eur(p['delta_1d'])} | {p['delta_pct']:+.2f}% |")
        out.append("")

    out += [
        "## Notes",
        "",
        f"_{len(market)} players tracked, {len(sc.start_pct)} with a "
        "probable-XI reading._",
        "",
        f"_xPts/j — expected points per jornada = shrunk pts/match "
        f"(K={shrink_k:.0f}"
        + (f", {hist_label}" if hist_label else ", **no points baseline**")
        + (f" + {cur_label}" if cur_label else "")
        + ") × fixture × P(start), from `ffcore/score.py` — the same scorer "
          "rivals.py uses. Injured, suspended and unavailable score zero; a "
          "doubt is halved. The fixture term is a ±%.0f%% band across the "
          "opponents ranked by %s, plus ±%.0f%% for home advantage; both "
          "widths are guesses, unfitted because nothing has been played, and "
          "small enough that a wrong one costs a fraction of a point._"
          % (FIX_BAND * 100, fix_basis_label(players), HOME_EDGE * 100),
        "",
        f"_Generated {now:%Y-%m-%d %H:%M} UTC._",
    ]

    write_lines(REPORTS / "latest.md", out)
    write_lines(HISTORY / f"{observed[:10]}.md", out)


def _selftest() -> None:
    """The cells that carry a judgement. main() needs a repo to run against;
    these do not, so they are the part CI can hold still."""
    def pl(pct=None, on_page=True, used=None, ppm=4.0, assumed=False):
        return {"pct": pct, "on_page": on_page, "ppm": ppm, "assumed": assumed,
                "pct_used": pct if used is None else used}

    # --- AF's two shapes, kept in their own units ---
    assert af_cell(None) == "—"                     # not joined at all
    assert af_cell({"role": "starter", "start_pct": ""}) == "titular"
    # A named starter is NOT rendered as a percentage: doing so would mean
    # inventing the yes→probability constant, and nothing exists to fit it.
    assert "%" not in af_cell({"role": "starter", "start_pct": ""})
    assert af_cell({"role": "starter", "start_pct": "100.0"}) == "100%"
    assert af_cell({"role": "doubt", "start_pct": "66.7"}) == "67%"
    assert af_cell({"role": "doubt", "start_pct": ""}) == "?"

    # --- FF's cell, and the marks that say "assumed", not "read" ---
    assert pct_cell(pl(pct=80.0)) == "80%"
    assert pct_cell(pl(on_page=True)).startswith("~")
    assert pct_cell(pl(on_page=False)).startswith("!")
    assert ppm_cell(pl(ppm=3.14)) == "3.1"
    assert ppm_cell(pl(ppm=3.14, assumed=True)) == "~3.1"

    # --- the disagreement that changes a decision, and the ones that don't ---
    starter = {"role": "starter", "start_pct": ""}
    out = {"role": "doubt", "start_pct": "33.3"}
    assert disagrees(pl(pct=90.0), starter, 60.0) == ""    # both say yes
    assert disagrees(pl(pct=10.0), out, 60.0) == ""        # both say no
    # FF has him starting, AF has him a third likely: that is the split.
    assert "33%" in disagrees(pl(pct=90.0), out, 60.0)
    assert "futbolfantasy 90%" in disagrees(pl(pct=90.0), out, 60.0)
    # And the reverse reads the other way round, AF first.
    rev = disagrees(pl(pct=10.0), starter, 60.0)
    assert rev.startswith(SECOND_SOURCE) and "titular" in rev
    # No second-source row is not a disagreement — it is silence.
    assert disagrees(pl(pct=90.0), None, 60.0) == ""

    # --- names ---
    # A particle stays lowercase inside a name, but not as its first word.
    assert title_name("nico van gaal") == "Nico van Gaal"
    assert title_name("de la fuente") == "De La Fuente"
    assert title_name("Vini Jr.") == "Vini Jr."      # already cased

    # --- teams, shortened without merging two clubs into one ---
    assert short_team("Real Madrid") == "Madrid"
    assert short_team("Real Sociedad") == "Sociedad"
    assert short_team("Atletico Madrid") == "Atletico"   # never "Madrid"
    assert short_team("Deportivo Alavés") == "Alavés"
    assert short_team("Real") == "Real"          # stripping to nothing: keep it
    assert short_team("") == ""

    # --- the fixture cells ---
    def fx(fix=1.0, opp="Elche", home=True):
        return {"fix": fix, "opp": opp, "home": home}

    assert vs_cell(fx(opp="")) == "—"            # no fixture is not a neutral
    assert fix_cell(fx(opp="")) == "—"
    assert vs_cell(fx(opp="Rayo Vallecano", home=False)) == "Rayo A"
    assert fix_cell(fx(1.0)) == "="              # median opponent
    assert fix_cell(fx(1.12)) == "+12%"
    assert fix_cell(fx(0.89)) == "-11%"
    # The star is a purchase-row marker only, because only those rows exclude
    # the fixture from their number.
    assert "★" not in vs_cell(fx(1.12))
    assert vs_cell(fx(1.12), star=True).endswith("★")
    assert vs_cell(fx(0.88), star=True).endswith("↓")
    assert vs_cell(fx(1.02), star=True) == "Elche H"     # too small to mark

    # --- a purchase is judged fixture-NEUTRAL ---
    def sq(name, flat, score, slot="DEL"):
        return {"name": name, "key": name, "slot": slot, "flat": flat,
                "score": score, "pos": slot}

    # Weak on merit, but he happens to face the bottom side: `score` says
    # upgrade, `flat` says no. flat_gains must follow flat.
    squad = [sq("mine", 5.0, 5.0, s) for s in ("POR",)] \
        + [sq("d%d" % i, 5.0, 5.0, "DEF") for i in range(5)] \
        + [sq("m%d" % i, 5.0, 5.0, "MED") for i in range(5)] \
        + [sq("f0", 5.0, 5.0, "DEL")]
    cheat = sq("cheat", 4.0, 9.0)
    real = sq("real", 6.0, 6.0)
    g = flat_gains(squad, [cheat, real])
    assert g["cheat"] < 0, g          # the easy fixture buys him nothing here
    assert abs(g["real"] - 1.0) < 1e-9, g
    # A player with no slot can never start, so he has no gain to report.
    assert flat_gains(squad, [sq("nopos", 9.0, 9.0, "")]) == {}

    # --- bid ceilings survive an overdrawn rival --------------------------
    # An overdrawn manager is a zero, not an unknown, so the ceiling is still
    # a number. When it was None, every bid in question 4 had to assume the
    # whole league could outspend you.
    class _M:
        def __init__(self, handle, bid):
            self.handle, self.max_bid = handle, bid

    class _LG(list):
        cfg = type("C", (), {"me": "me"})()

    lg = _LG([_M("me", 50e6), _M("broke", 0.0), _M("rich", 30e6)])
    assert rival_ceiling(lg) == 30e6, rival_ceiling(lg)
    # Genuinely unknown still suppresses it, which is the case it exists for.
    assert rival_ceiling(_LG([_M("me", 50e6), _M("who", None)])) is None

    # --- λ: what the report prints when there is no rate to print ---------
    # A missing rate is never a zero hurdle, and the reason is in the section
    # rather than left as a blank table. This is the case that fires on a
    # half-configured repo, which is the one most likely to be misread.
    none_lam = Lambda(None, [], 0.0, 0.0, "no cash to price it with")
    txt = "\n".join(sec_ladder(none_lam, 0.25))
    assert "no cash to price it with" in txt
    assert "|" not in txt                      # no table, so nothing to misread
    # With a ladder, the LAST rung is marked as λ: it is the rate, and the ones
    # above it are what the money buys before it runs out.
    from ffcore.bid import Rung
    lam = Lambda(0.5, [Rung("cheap", "DEF", 2.0, 1e6, 2.0),
                       Rung("dear", "MED", 1.0, 2e6, 0.5)], 5e6, 3e6, "two")
    body = "\n".join(sec_ladder(lam, 0.2))
    assert "| 2 ←λ | dear |" in body, body
    assert "| 1 | cheap |" in body
    assert "hurdle 0.60" in body               # 0.5 x (1 + 0.2)

    # --- which scale ranked the opponents, said out loud ------------------
    assert fix_basis_label([{"opp": "Elche", "fix_basis": "elo"}]) \
        == "Club Elo rating"
    # One Elo row is enough to name it, because the board refuses a mixture.
    assert fix_basis_label([{"opp": "A", "fix_basis": "value"},
                            {"opp": "B", "fix_basis": "elo"}]) \
        == "Club Elo rating"
    assert "wallet" in fix_basis_label([{"opp": "A", "fix_basis": "value"}])
    # A squad with no fixtures at all is not "ranked by value" — it is unranked.
    assert "no fixture is known" in fix_basis_label(
        [{"opp": "", "fix_basis": "none"}])

    print("report self-test OK (52 cases)")


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        _selftest()
        raise SystemExit(0)
    main()
