"""
report.py — daily decision report, written as markdown into the repo.

Renders in the GitHub mobile app, so it's readable anywhere with no hosting.
Run after ingest.py parse.

    python src/report.py

Structure, top to bottom: what needs a decision today, today's market slate
priced player by player, your team as one table (XI then bench, with the cost
of each swap), and your own squad's price moves. League-wide movers and
recruitment live in reports/watchlist.md; how your rivals behave lives in
reports/rivals.md.

THE SLATE IS THE REPORT when you paste one into inputs/seen.txt. The app deals
a limited market, so a ranked list of everyone unowned is mostly players you
cannot buy. sec_slate() answers the only live question — of the players on
offer right now, which improve my XI, what should I bid, and who else wants
them — using ffcore.bid: the XI index gained by owning him, and the floor plus
the premium this league has actually paid over it. How many purchases went at
the floor is counted from the ledger on every run rather than stated here,
because the sentence that stated it went stale inside a fortnight (issue #23).

SCORING lives in ffcore/score.py now, shared with rivals.py so that your
squad and theirs are ranked by the same arithmetic:

    score = shrunk points-per-match  x  P(start)

It is a RANKING INDEX, not a points forecast, and it cannot know three
things — all flagged in the report rather than hidden: promoted-side players
carry an assumed baseline, absence from the probable-XI page is not the same
as a blank percentage there, and none of it has been checked against reality
yet. Every snapshot appends the whole squad, XI and bench, with the inputs
that produced each score, to data/decisions/squad_log.csv, so that once
jornadas exist you can ask what the ranking cost you.

MIGRATED onto ffcore. Four things changed in substance:

  * fold(), num(), eur(), read_csv(), latest_only(), parse_stamp() and
    input_path() are gone — they were local copies. norm() in particular
    now matches the rest of the repo, so a name with an apostrophe or an
    initial joins the same way here as it does in squads.py.
  * The scorer is imported, not defined. Tuning SHRINK_K used to require
    editing two files that could silently disagree.
  * Cash comes from ffcore.league, which also reads rival balances and
    understands a time-of-day on the anchor. The old regex read the first
    number in the file and assumed midnight.
  * Your squad comes from the ledger via ffcore.league. inputs/squad.txt is
    still generated by squads.py and still works as a fallback, but it is no
    longer the source of truth.
"""

from __future__ import annotations

import os
import re
import sys
from collections import Counter
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ffcore.bid import (HOLD_DAYS, band_of, deals,  # noqa: E402
                        demand_summary, drift_bands, friction, gain,
                        premiums, suggest, verdict, xi_snapshots)
from ffcore.league import League  # noqa: E402
from ffcore.parse import money, ratio  # noqa: E402
from ffcore.score import (ABSENT_START, MAX_SLOT, NEUTRAL_START,  # noqa: E402
                          SLOT_LABEL, SLOT_MIN, THIN, Scorer, formations,
                          pick_xi, squad_pool)
from ffcore.tidy import (DECISIONS, MADRID, REPORTS, SEASON,  # noqa: E402
                         append_csv, input_path, latest_only, load_deadline,
                         load_market, load_lineups, read_csv, snapshot_stamp,
                         write_lines)
from seen import read_slate  # noqa: E402

HISTORY = REPORTS / "history"

STALE_HOURS = 14.0
MOVER_PCT = 1.0           # squad price moves worth printing

# The second probable-XI source. futbolfantasy is the primary — it is what the
# scorer reads — and this one is printed BESIDE it, never blended into it.
SECOND_SOURCE = "analitica"

# Name particles that stay lowercase when title-casing a folded name.
# "le"/"el"/"la" are deliberately absent: Le Normand and El Hilali are far
# more common in this league than "de la Fuente" losing its lowercase.
PARTICLES = {"de", "del", "van", "von", "der", "den", "di", "da", "dos",
             "do", "y", "bin", "ibn", "ter"}


def title_name(s: str) -> str:
    """market.csv hands us folded names; make them readable again.

    Accents survive (they're in the source string), particles stay lowercase,
    hyphenated parts are capitalised on both sides. Moves to ffcore/render.py
    when the other reports are migrated.
    """
    s = (s or "").strip()
    if not s or s != s.lower():
        return s  # already cased — leave it alone
    words = []
    for i, w in enumerate(s.split()):
        if i and w in PARTICLES:
            words.append(w)
        else:
            words.append("-".join(p[:1].upper() + p[1:] for p in w.split("-")))
    return " ".join(words)


def eur(v) -> str:
    if v is None:
        return "—"
    v = float(v)
    if abs(v) >= 1_000_000:
        return f"{v/1_000_000:.2f}M"
    if abs(v) >= 1_000:
        return f"{v/1_000:.0f}K"
    return f"{v:.0f}"


def load_history() -> tuple[dict, str]:
    """{normalised name: {'pts','pj'}} from the newest points_*.csv."""
    from ffcore.text import norm
    files = sorted(SEASON.glob("points_*.csv")) if SEASON.exists() else []
    if not files:
        return {}, ""
    out: dict[str, dict] = {}
    for r in read_csv(files[-1]):
        rec = {"pts": ratio(r.get("points")) or 0.0,
               "pj": ratio(r.get("games")) or 0.0}
        for key in (r.get("player_name"), r.get("player_name_full")):
            if key:
                out.setdefault(norm(key), rec)
    return out, files[-1].stem.replace("points_", "")


def as_fielded(players, squad):
    """(total, xi, bench, illegal, warnings) for the XI you have MARKED.

    Reads inputs/lineup.txt — the checklist squads.py regenerates — so the
    report can say what your actual eleven is worth, not only what the best
    one would be. Returns None when there is no checklist to read: the
    comparison is skipped, never faked from the recommendation.

    `illegal` is the shape when the marks do not make a legal eleven, which
    is worth flagging louder than a suboptimal one — the app will fill the
    gap for you, and not with your choice.
    """
    from ffcore.text import norm
    from xi import bench_from_checklist, read_checklist

    path = input_path("lineup.txt")
    if not path.exists():
        return None
    entries = read_checklist(path.read_text(encoding="utf-8"))
    if not entries:
        return None

    names = [p["name"] for p in players]
    bench_keys, warnings = bench_from_checklist(names, entries)
    benched = {norm(b) for b in bench_keys}
    xi = [p for p in players if norm(p["name"]) not in benched]
    bench = [p for p in players if norm(p["name"]) in benched]

    counts = Counter(p["slot"] for p in xi if p["slot"])
    shape = (counts.get("DEF", 0), counts.get("MED", 0), counts.get("DEL", 0))
    illegal = None
    if len(xi) != 11 or counts.get("POR", 0) != 1 or shape not in set(
            formations()):
        illegal = "%d players, %d-%d-%d" % ((len(xi),) + shape)
    return sum(p["score"] for p in xi), xi, bench, illegal, warnings


def swaps(fielded_xi, best_xi):
    """[(out, in)] — who to bench for whom, paired within a position.

    Only same-slot pairs are offered. A cross-slot difference is a change of
    formation, not a substitution, and printing it as one would suggest an
    illegal move.
    """
    from ffcore.text import norm

    best_keys = {norm(p["name"]) for p in best_xi}
    out_ = [p for p in fielded_xi if norm(p["name"]) not in best_keys]
    have = {norm(p["name"]) for p in fielded_xi}
    in_ = [p for p in best_xi if norm(p["name"]) not in have]
    pairs = []
    for o in sorted(out_, key=lambda p: p["score"]):
        cand = [i for i in in_ if i["slot"] == o["slot"]]
        if cand:
            best_in = max(cand, key=lambda p: p["score"])
            in_.remove(best_in)
            pairs.append((o, best_in))
    return pairs


def load_squad_file() -> list[str]:
    """inputs/squad.txt — fallback only. The ledger is the source of truth."""
    path = input_path("squad.txt")
    if not path.exists():
        return []
    return [ln.strip() for ln in path.read_text(encoding="utf-8").splitlines()
            if ln.strip() and not ln.strip().startswith("#")]


def squad_names(lg) -> tuple[list[str], str]:
    """Your roster, and where it came from."""
    if lg is not None:
        mine = lg.managers.get(lg.cfg.me)
        if mine and mine.players:
            by_key = lg.market.latest() if lg.market else {}
            return ([by_key.get(k, {}).get("name", k) for k in mine.players],
                    "ledger")
    return load_squad_file(), "squad.txt"


def rival_ceiling(lg) -> float | None:
    """Largest bid any rival could still make, or None if any cash is unknown.

    An unknown balance is not a zero. Returning None where one rival's cash
    cannot be reconstructed is what stops suggest() telling you to bid the
    floor against someone who can outspend you.
    """
    bids = [m.max_bid for m in lg if m.handle != lg.cfg.me]
    if not bids or any(b is None for b in bids):
        return None
    return max(bids)


def sec_slate(lg, sc, by_key, pool, tot, slate, prem, cash_value,
              rival_max, snaps, sell_prem=None,
              bands=None) -> tuple[list[str], int, int]:
    """Today's slate, priced. The only section that answers 'what do I do now'.

    Everything else in this report describes a position; this one is a list of
    purchases you can make in the next few minutes, so it leads. XI gain is the
    change in the ranking index from owning him and re-picking the formation —
    it is what he is worth to you, and it is frequently negative for a player
    the watchlist ranks highly, because your own eleven is the benchmark.
    """
    on_offer, unresolved, ambiguous, auto = slate
    out: list[str] = []

    owned = {k: lg.owner[k] for k in on_offer if k in lg.owner}

    rows = []
    for k in on_offer:
        if k in owned:
            continue
        rec = by_key.get(k)
        if not rec:
            continue
        cand = sc.score(rec).as_row()
        cand["name"] = title_name(cand["name"])
        g = gain(pool, cand, tot) if tot is not None else None
        adv = suggest(cand["value"], prem, cash_value, rival_max)
        # How far below the thin threshold you are in HIS position. This is
        # what turns a negative-gain forward into cover rather than a pass.
        slot = cand.get("slot")
        short_by = (max(0, THIN[slot] - len(pool.get(slot, [])))
                    if slot in THIN else 0)
        daily_pct, n_drift = (bands or {}).get(band_of(cand["value"]),
                                               (0.0, 0))
        fr = friction(cand["value"], prem, sell_prem, daily_pct, n_drift)
        rows.append((cand, g, adv, short_by, fr))

    # Best upgrade first. A player who cannot start sorts last whatever his
    # score, because the question here is what he adds to YOUR eleven.
    # Cover first when you cannot field a legal XI without it, then by gain.
    rows.sort(key=lambda r: (-r[3] if r[1] is not None and r[1] <= 0 else 0,
                             r[1] is None, -(r[1] or 0.0), -r[0]["score"]))
    better = sum(1 for _, g, _, _, _ in rows if g is not None and g > 0)
    covers = sum(1 for _, g, a, sb, _ in rows
                 if sb > 0 and a.low is not None and g is not None)

    out += ["## 4. Anything to do in the market?", "",
            "**%d on offer, %d improve your XI%s.**"
            % (len(rows), better,
               ", %d cover a position you are short in" % covers
               if covers else ""), ""]
    if not rows:
        out += ["_Every name you pasted is either already owned or missing "
                "from the market data._", ""]
    else:
        out += ["| Player | Pos | Value | Start% | XI gain | Bid | Cost/pt | "
                "Competition | Verdict |",
                "|---|---|--:|--:|--:|--:|--:|---|---|"]
        for cand, g, adv, short_by, fr in rows:
            band = ("—" if adv.low is None
                    else eur(adv.low) if abs(adv.high - adv.low) < 1_000
                    else "%s–%s" % (eur(adv.low), eur(adv.high)))
            cpp = fr.per_point(g) if fr else None
            out.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
                cand["name"], (cand["pos"] or "—")[:3], eur(cand["value"]),
                "—" if cand["pct"] is None else "%.0f%%" % cand["pct"],
                "—" if g is None else "%+.1f" % g,
                band, "—" if cpp is None else eur(cpp),
                demand_summary(cand, lg, snaps),
                verdict(g, adv, short_by)))
        out += ["",
                "**Cost/pt** is what the marginal point actually costs, and "
                "it is not the price: a purchase is closer to a loan than a "
                "spend, because the value comes back when you sell. It is the "
                "premium you pay over the floor plus the value expected to "
                "drain away over %d days — NOT the price, and NOT the exit. "
                "The app pays value give or take %s on a sale, which on a "
                "large player is bigger than both other terms together; that "
                "swing is a coin flip, so it is stated here rather than "
                "averaged into a number that would look like a price. "
                "Drift is a flat mean within his price band, over readings "
                "taken before a ball was kicked — expect it to move harder "
                "once results land."
                % (HOLD_DAYS,
                   ("%.0f%%" % sell_prem.swing() if sell_prem
                    else "about a tenth")),
                "",
                "Competition is demand, not roster counts: the rivals whose "
                "XI actually improves with him, strongest threat first — "
                "`?` cash unknown (treat as live), `(n broke)` want him but "
                "cannot pay the floor. The full manager-by-manager matrix is "
                "in `reports/rivals.md`.", "",
                "Bid is the floor plus what this league has actually paid over "
                "it: %s.%s A dozen deals is not a distribution — the range is "
                "what has happened, not a chance of winning, and every one of "
                "them is a bid that won."
                % (prem.label() if prem else
                   "no priced purchase yet, so these are floors",
                   ("" if not prem else
                    " %d of those %d went at the floor itself, so the minimum "
                    "is not a number known to lose." % (prem.at_floor, prem.n)
                    if prem.at_floor else
                    " None of those %d went at the floor." % prem.n)), ""]
        if rival_max is None:
            out += ["_At least one rival's cash is an estimate, so no bid here "
                    "assumes you are unopposed._", ""]
        if cash_value is None:
            out += ["_Your own balance is not a recorded number, so no bid is "
                    "capped by what you actually have. Put it in "
                    "`inputs/cash.txt`._", ""]

    if owned:
        out += ["Already owned, so not a purchase: %s." % ", ".join(
            "%s (%s)" % (by_key.get(k, {}).get("name", k),
                         "you" if h == lg.cfg.me else h)
            for k, h in sorted(owned.items())), ""]

    if auto:
        # Printed, not hidden: this is the one place the repo guesses between
        # candidates, and it guesses off a ledger you maintain by hand. If a
        # line here names the wrong player, the fix is a missing row in
        # transactions.csv (issue #26).
        out += ["**Placed by ownership, not by the name.** The app deals free "
                "agents, so a candidate somebody already holds is not the one "
                "on offer — check these if one looks wrong:", ""]
        out += ["- " + a for a in auto] + [""]

    if unresolved or ambiguous:
        # A heading, not bold text, so digest.py prints it once instead of
        # repeating the watchlist's copy of the same list.
        out += ["## Names I could not place", "",
                "OCR mangled these past matching, so they are missing from "
                "the table above — re-read them off the app if one matters.",
                ""]
        out += ["- **%s** — no match" % u for u in unresolved]
        out += ["- **%s** — could be %s" % (raw, ", ".join(c))
                for raw, c in ambiguous]
        out.append("")
    return out, len(rows), better


def log_squad(observed, players, chosen, formation, total, deadline,
              obs_dt) -> None:
    """Append-only record of every recommendation, for scoring later.

    One row per player per snapshot — long format, so a scorer can group by
    snapshot without parsing packed strings. hours_to_lock is stored rather
    than an at-lock flag, because a run cannot know whether a later snapshot
    will still beat the deadline: the scorer picks, per jornada, the row with
    the smallest non-negative value.

    The bench is logged too. Without it "what did the ranking cost me" is
    unanswerable after the fact, and that is the whole point of keeping this.
    """
    path = DECISIONS / "squad_log.csv"
    if observed in {r.get("observed_at") for r in read_csv(path)}:
        return
    htl = ""
    if deadline and obs_dt:
        htl = f"{(deadline - obs_dt).total_seconds() / 3600:.1f}"
    cols = ["observed_at", "hours_to_lock", "formation", "index_total",
            "player", "pos", "slot", "start_pct", "start_source", "status",
            "assumed", "value", "score", "picked"]
    rows = []
    for p in players:
        src = ("read" if p["pct"] is not None
               else "listed_blank" if p["on_page"] else "absent")
        rows.append({
            "observed_at": observed, "hours_to_lock": htl,
            "formation": "-".join(str(x) for x in formation),
            "index_total": f"{total:.2f}",
            "player": p["name"], "pos": p["pos"], "slot": p["slot"],
            "start_pct": "" if p["pct"] is None else f"{p['pct']:.0f}",
            "start_source": src, "status": p["status"] or "ok",
            "assumed": int(bool(p["assumed"])),
            "value": f"{p['value']:.0f}", "score": f"{p['score']:.3f}",
            "picked": int(id(p) in chosen),
        })
    append_csv(path, rows, cols)


# ---------------------------------------------------------------------------
# The four questions
#
# These four sections open the report, in this order, because they are the
# four things you can still act on before the lock. Everything else — premium
# curves, drift, full rosters, deal history, methodology — is reference and
# lives below the fold or in its own file.
#
# Question 1 leads with WHAT YOU ARE FIELDING, not with what the model would
# field. The marks in inputs/lineup.txt are a fact; the recommendation is
# advice, and printing advice as though it were the team is how the old report
# managed to show two different benches under the same word.
# ---------------------------------------------------------------------------

STATE_LABEL = {
    "injured": "🔴 injured",
    "suspended": "🔴 suspended",
    "unavailable": "🔴 unavailable",
    "doubt": "🟡 doubt",
    "ok": "fit",
}


def sec_eleven(marked, best, players, second=None) -> list[str]:
    """## 1. Am I fielding the right eleven?"""
    out = ["## 1. Am I fielding the right eleven?", ""]

    if not players:
        return out + ["_No roster. Check `inputs/rosters_initial.txt` and "
                      "`inputs/transactions.csv`._", ""]
    if marked is None:
        return out + ["_No marks to read. `inputs/lineup.txt` is missing or "
                      "empty — run `squads.py`, then tick the eleven you are "
                      "fielding._", ""]

    mtot, mxi, mbench, illegal, mwarn = marked
    counts = Counter(p["slot"] for p in mxi if p["slot"])
    shape = "%d-%d-%d" % (counts.get("DEF", 0), counts.get("MED", 0),
                          counts.get("DEL", 0))

    if illegal:
        out += [f"**⚠ Not a legal eleven — {illegal}.** The app will fill the "
                "gaps for you, and not with your choice. Fix "
                "`inputs/lineup.txt`.", ""]
    else:
        out += [f"**Your XI: {shape} · ≈{mtot:.0f} pts expected next "
                "jornada** (uncalibrated — see the methodology link at the "
                "end)", ""]

    # Three readings side by side, not one blended number: the points a player
    # scores per match, and each source's view of whether he plays. Only the
    # first is shared — points per match is a record, and both sites are
    # looking at the same one — so blending is only ever tempting for the two
    # start columns, and that is exactly where it would hide a disagreement
    # worth seeing. State has moved to question 2, which prints every player.
    cells = second or {}
    out += ["| | Marked XI | pts/m | FF | AF | xPts/j |",
            "|---|---|--:|--:|--:|--:|"]
    for slot in ("POR", "DEF", "MED", "DEL"):
        for p in [x for x in mxi if x["slot"] == slot]:
            flag = " ⚠" if (p["status"] or "ok") != "ok" else ""
            out.append(f"| {slot} | {p['name']}{flag} | {ppm_cell(p)} | "
                       f"{pct_cell(p)} | {af_cell(cells.get(p['key']))} | "
                       f"{p['score']:.1f} |")
    out += ["",
            "_**pts/m** is points per match from last season's totals, shrunk "
            "toward the average for a short record — a record, not a "
            "fixture-aware forecast: it does not know who the opponent is. "
            "`~` means no top-flight record at all, so the baseline is "
            "assumed. **FF** is futbolfantasy's published start percentage, "
            "**AF** is analiticafantasy's; they are separate columns because "
            "neither has been checked against a played jornada yet, so there "
            "is no weight to blend them by. **xPts/j** = pts/m × FF, and uses "
            "FF only. `⚠` on a name means question 2 has something on him._",
            ""]

    if best is None:
        return out + ["_No legal XI available from this squad, so there is "
                      "nothing to compare against._", ""]

    btot, (d, m, f), bxi = best
    gap = btot - mtot
    if gap <= 0.05:
        out += [f"**Nothing to change.** The model's best legal XI is the same "
                f"eleven ({d}-{m}-{f}, ≈{btot:.0f} pts).", ""]
        return out

    pairs = swaps(mxi, bxi)
    out += [f"**The model would score ≈{btot:.0f} — {gap:.1f} pts/j more.** "
            f"Its shape is {d}-{m}-{f}.", ""]
    if not pairs:
        out += ["_The difference is a change of formation, not a substitution, "
                "so there is no like-for-like swap to offer._", ""]
        return out

    out += ["| Bench this | For this | Worth |", "|---|---|--:|"]
    for o, i in pairs:
        out.append(f"| {o['name']} ({o['score']:.1f}) | "
                   f"{i['name']} ({i['score']:.1f}) | "
                   f"{i['score'] - o['score']:+.1f} |")
    out += ["", "_Swaps are same-position only: a cross-slot difference is a "
                "change of formation, not a substitution. Your own marks are "
                "the row above — this table is advice._", ""]

    for w in mwarn:
        out.append(f"- ⚠ {w}")
    if mwarn:
        out.append("")
    return out


def sec_fitness(players) -> list[str]:
    """## 2. Is anyone injured, suspended, or doubtful?

    Every squad member gets a row, including the ones nothing is known about.
    Silence and fitness must not look the same: an empty section used to be
    indistinguishable from a clean bill of health, and for the whole life of
    this repo that is exactly what it was — the status column was dead.
    """
    out = ["## 2. Is anyone injured, suspended, or doubtful?", ""]
    if not players:
        return out + ["_No roster to check._", ""]

    flagged = [p for p in players if p["status"] and p["status"] != "ok"]
    nodata = [p for p in players if not p["on_page"]]
    fit = [p for p in players
           if p["on_page"] and (not p["status"] or p["status"] == "ok")]

    if flagged:
        out += [f"**{len(flagged)} of {len(players)} flagged.**", ""]
    else:
        out += [f"**Nobody in your squad is flagged.** All {len(fit)} players "
                "with an entry on their team page read as available.", ""]

    # Rows for what is wrong or unknown; one line for what is fine. Every
    # player is still accounted for — the guarantee above is that silence and
    # fitness must not look the same, and they do not: a no-data player keeps
    # his own row and the fit ones are named, not merely counted. What is gone
    # is fifteen table rows reading "fit | listed, no flag" on a phone screen.
    if flagged or nodata:
        out += ["| Player | State | What the page says |", "|---|---|---|"]
        order = {"injured": 0, "suspended": 1, "unavailable": 2, "doubt": 3}
        for p in sorted(flagged, key=lambda x: order.get(x["status"], 9)):
            out.append(f"| {p['name']} | "
                       f"{STATE_LABEL.get(p['status'], p['status'])}"
                       f" | {p['note'] or '—'} |")
        for p in sorted(nodata, key=lambda x: x["name"]):
            out.append(f"| {p['name']} | ⚪ no data | not listed on his team "
                       "page — unknown, not fit |")
        out.append("")
    if fit:
        out += [f"_Listed with no flag ({len(fit)}): "
                + ", ".join(p["name"] for p in sorted(fit,
                                                      key=lambda x: x["name"]))
                + "._", ""]

    if nodata:
        out += [f"_{len(nodata)} player(s) have no entry on their team page. "
                "That is an absence of evidence, not evidence of fitness — "
                "check them in the app before the lock._", ""]
    out += ["_Read from the 'Estado físico', 'Sancionados' and 'No "
            "disponibles' blocks of each team page. A knock the site still "
            "lists as available (`Tocado`) is folded into doubt._", ""]
    return out


def pct_cell(p) -> str:
    """Start percentage, marked when it is an assumption rather than a
    reading. `~` = listed with no figure, `!` = not on the page at all."""
    if p["pct"] is not None:
        return f"{p['pct']:.0f}%"
    return ("~" if p["on_page"] else "!") + \
        f"{NEUTRAL_START if p['on_page'] else ABSENT_START:.0f}%"


def load_second(players, source: str = SECOND_SOURCE):
    """{player key: the second source's row}, plus the names it could not join.

    Joined by name — exact first, then ffcore.text.resolve — because the two
    sites number players differently and neither publishes the app's slug.
    Nothing is guessed: a name with several candidates is handed back to be
    printed, not picked between, and it carries no cell in the table.
    """
    from ffcore.text import resolve

    rows = latest_only(load_lineups(source))
    cells: dict = {}
    unclear: list[tuple[str, list[str]]] = []
    for p in players:
        row, cands = resolve(p["name"], rows, key="player_name")
        if row:
            cells[p["key"]] = row
        elif cands:
            unclear.append((p["name"], [c["player_name"] for c in cands]))
    return cells, unclear


def af_cell(row) -> str:
    """The second source's read, in its own units.

    It publishes two different things on the same page, and they are not
    interchangeable. Close to kickoff it names a starting eleven — a final
    call, with no number attached. Before that it publishes its editors'
    consensus as a fraction ("2/3 titular"), which IS a probability and is
    printed as one. A final call is printed as `titular`, never dressed up as
    100%, because turning a yes into a percentage would mean inventing the
    constant that converts them, and no jornada has been played to fit it.
    """
    if not row:
        return "—"
    pct = row.get("start_pct")
    if pct not in (None, ""):
        return f"{float(pct):.0f}%"
    return "titular" if row.get("role") == "starter" else "?"


def ppm_cell(p) -> str:
    """Points per match. `~` marks a player with no top-flight record, whose
    baseline is assumed rather than earned."""
    return ("~" if p["assumed"] else "") + f"{p['ppm']:.1f}"


def disagrees(p, row, min_start: float) -> str:
    """Why the two sources conflict for this player, or ''.

    Only a conflict that would change the decision counts: one source putting
    him in the eleven while the other does not.
    """
    if not row:
        return ""
    likely = p["pct_used"] >= min_start
    named = (row.get("role") == "starter"
             or (row.get("start_pct") not in (None, "")
                 and float(row["start_pct"]) >= min_start))
    if likely and not named:
        return f"futbolfantasy {pct_cell(p)}, {SECOND_SOURCE} {af_cell(row)}"
    if named and not likely:
        return f"{SECOND_SOURCE} {af_cell(row)}, futbolfantasy {pct_cell(p)}"
    return ""


def sec_starting(marked, players, min_start, second=None,
                 unclear=None) -> list[str]:
    """## 3. Is everyone expected to start?

    EXCEPTIONS ONLY. This used to print all fifteen players with a Reading
    column, and on a normal day fourteen of those rows read "published" — a
    column of the same word, pushing the one row that mattered off a phone
    screen. Every start figure is now in question 1's table, so what belongs
    here is only what question 1 cannot show: who is under the threshold, and
    where the two sources contradict each other.
    """
    out = ["## 3. Is everyone expected to start?", ""]
    if marked is None:
        return out + ["_No marks to read — see question 1._", ""]

    cells = second or {}
    _, mxi, mbench, _, _ = marked
    low = [p for p in mxi if p["pct_used"] < min_start]
    split = [(p, lab, why) for lab, group in (("XI", mxi), ("bench", mbench))
             for p in group
             for why in [disagrees(p, cells.get(p["key"]), min_start)] if why]

    if not low and not split and not unclear:
        out += [f"**Nothing to check.** Every marked player is at "
                f"{min_start:.0f}% or above on futbolfantasy, and "
                f"analiticafantasy does not contradict any of them.", ""]
    if low:
        out += [f"**{len(low)} of your marked XI are under {min_start:.0f}%:** "
                + ", ".join(f"{p['name']} ({pct_cell(p)})" for p in low)
                + ".", ""]
    if split:
        out += ["**The two sources disagree** — one of them has him in the "
                "eleven and the other does not. Neither has a track record "
                "here yet, so this is a prompt to open the app, not a verdict:",
                ""]
        out += ["| | Player | The split |", "|---|---|---|"]
        for p, lab, why in split:
            out.append(f"| {lab} | {p['name']} | {why} |")
        out.append("")
    if unclear:
        out += [f"_{len(unclear)} name(s) could not be matched to "
                f"analiticafantasy without guessing, so they carry no AF cell: "
                + "; ".join(f"**{n}** → {', '.join(c)}" for n, c in unclear)
                + ". A wrong player is worse than a blank one._", ""]

    out += ["_Both figures are editorial reads refreshed a few times a day, "
            "not live probabilities. `~` means listed with no figure "
            f"(assumed {NEUTRAL_START:.0f}%), `!` not on the page at all "
            f"(assumed {ABSENT_START:.0f}%). Threshold is `min_start` in "
            "`inputs/league.ini`._", ""]
    return out


def main() -> None:
    all_market = load_market()
    market = latest_only(all_market)
    xi_rows = latest_only(load_lineups())

    REPORTS.mkdir(exist_ok=True)
    HISTORY.mkdir(parents=True, exist_ok=True)

    if not market:
        write_lines(REPORTS / "latest.md", [
            "# Fantasy report", "",
            "No market data in `data/tidy/market.csv`. "
            "Did `ingest.py parse` run?"])
        print("no market data; wrote placeholder report")
        return

    try:
        lg = League.load()
    except SystemExit as exc:
        # rosters_initial.txt missing — fall back to squad.txt so a
        # half-configured repo still produces a report.
        print("league not loaded (%s); using squad.txt" % exc)
        lg = None

    hist, hist_label = load_history()
    shrink_k = lg.cfg.shrink_k if lg else 8.0
    sc = Scorer(market, xi_rows, hist, shrink_k=shrink_k)

    observed = market[0]["observed_at"]
    obs_dt = snapshot_stamp(observed)
    now = datetime.now(timezone.utc)
    age_h = (now - obs_dt).total_seconds() / 3600 if obs_dt else None

    # --- build squad records ---------------------------------------------
    squad, squad_src = squad_names(lg)
    scored, missing = sc.score_squad(squad)
    players = []
    for s in scored:
        row = s.as_row()
        row["name"] = title_name(row["name"])
        players.append(row)
    squad_value = sum(p["value"] for p in players)

    pool = squad_pool(players)
    best = pick_xi(pool) if players else None
    chosen = {id(p) for p in best[2]} if best else set()

    # --- today's slate ----------------------------------------------------
    # Built before the header because the count belongs in the alerts: when a
    # slate has been pasted, it is the decision, and the rest of the report is
    # the position it is being made from.
    cash = lg[lg.cfg.me].cash if lg and lg.cfg.me in lg.managers else None
    cash_value = cash.value if cash and cash.confidence == "known" else None
    by_key = lg.market.latest() if lg and lg.market else {}
    slate = read_slate(by_key, lg.owner) if by_key else (set(), [], [], [])
    # Priced once: the buy side sizes a bid, and the sell side is what the app
    # pays you for a player, which the bench table needs whether or not a slate
    # was pasted.
    dl = deals(lg, lg.market) if lg and lg.market else []
    app_prem = premiums(dl, "sell")
    slate_lines, n_slate, n_better = [], 0, 0
    if any(slate):
        # The same snapshots rivals.py prints in its section 6, so the
        # Competition column and the matrix can never disagree.
        snaps = xi_snapshots(lg, sc, by_key)
        slate_lines, n_slate, n_better = sec_slate(
            lg, sc, by_key, pool, best[0] if best else None, slate,
            premiums(dl), cash_value, rival_ceiling(lg), snaps,
            sell_prem=app_prem, bands=drift_bands(all_market))

    # --- assemble ---------------------------------------------------------
    # Four questions, four tables, then a rule and everything else. The old
    # layout led with the recommendation and buried the marked XI in a
    # footnote; this inverts it.
    marked = as_fielded(players, squad) if players else None
    min_start = lg.cfg.min_start if lg else 60.0
    second, unclear = load_second(players)

    out: list[str] = [f"# Fantasy report — {observed}", ""]

    ctx = []
    # Derived from the next kickoff when fixtures have been scraped, so it
    # cannot go stale the way a typed date did. The source is printed: a
    # deadline you cannot trace is one you stop trusting.
    deadline, dl_src = load_deadline(with_source=True)
    if deadline:
        left = (deadline - now).total_seconds() / 3600
        if left < 0:
            ctx.append("**Deadline passed** — update `inputs/deadline.txt`")
        elif left < 48:
            ctx.append(f"**Locks in {left:.0f}h**"
                       + (" (next kickoff)" if dl_src == "fixtures" else ""))
        else:
            ctx.append(f"Locks in {left / 24:.0f} days")
    ctx.append(f"squad {eur(squad_value)}")
    if cash and cash.value is not None:
        ctx.append(f"cash {cash.label()}")
        ctx.append(f"total {eur(squad_value + cash.value)}")
    out += [" · ".join(ctx), ""]

    out += sec_eleven(marked, best, players, second)
    out += sec_fitness(players)
    out += sec_starting(marked, players, min_start, second, unclear)
    out += (slate_lines if slate_lines else
            ["## 4. Anything to do in the market?", "",
             "_No slate pasted, so there is nothing you can bid on today that "
             "this report knows about. Paste today's market screenshot into "
             "the `seen` input to price it. Everyone unowned is ranked in "
             "`reports/watchlist.md`._", ""])

    out += ["---", ""]

    # --- below the fold ---------------------------------------------------
    warnings: list[str] = []
    if age_h is not None and age_h > STALE_HOURS:
        warnings.append(f"**Data is {age_h:.0f}h old** — the ingest workflow "
                        "may have failed. Everything above is that snapshot.")
    if best:
        for k, n in THIN.items():
            have = len(pool.get(k, []))
            if have < n:
                warnings.append(f"**Only {have} {SLOT_LABEL[k]}"
                                f"{'s' if have != 1 else ''}** — one knock and "
                                "you can't field a legal XI.")
        guessed = [p["name"] for p in best[2] if p["assumed"]]
        if guessed:
            warnings.append(f"**{len(guessed)} unmodelled** "
                            f"({', '.join(guessed)}) — no LaLiga record, so "
                            "they carry an assumed baseline, not an earned "
                            "one.")
    if missing:
        warnings.append("**Not found in the market:** "
                        + ", ".join(f"`{m}`" for m in missing)
                        + " — check them with find_slug.py.")
    if cash and cash.value is not None and cash.confidence != "known":
        warnings.append("Cash is an estimate — record an observed balance in "
                        "`inputs/cash.txt`.")
    elif cash and cash.value is not None:
        last_tx = max((t.get("date") or "" for t in lg.txns), default="")
        anchor = re.search(r"\d{4}-\d{2}-\d{2}", cash.basis or "")
        if anchor and last_tx and last_tx[:10] > anchor.group(0):
            warnings.append(f"Balance last checked {anchor.group(0)}, but the "
                            f"ledger moved on {last_tx[:10]}. Re-check it.")
    elif not cash or cash.value is None:
        warnings.append("No cash figure — add `inputs/cash.txt`.")

    out += ["## Warnings", ""]
    out += ([f"- {w}" for w in warnings] if warnings
            else ["_Nothing flagged._"])
    out += ["", "_Compare squad value with the app; a mismatch means a name "
                f"matched the wrong player. Roster read from the "
                f"{squad_src}._", ""]

    # --- not in your XI ---------------------------------------------------
    # THIS IS THE BENCH. The word used to name two different lists in the same
    # report — the model's spare players in one place, your marks in another.
    # There is now exactly one bench, and it is yours; the model's opinion is
    # the swap table in question 1.
    if players and best:
        tot, (d, m, f), picked = best
        spare = (marked[2] if marked else
                 [p for p in players if id(p) not in chosen])
        source = ("as you have marked them" if marked
                  else "model's spare players — no checklist to read")
        out += [f"## Not in your XI ({source})", ""]
        if not spare:
            out += ["_Nobody spare._", ""]
        else:
            rank = {id(p): i for v in pool.values() for i, p in enumerate(v)}
            rows = []
            for p in spare:
                forced = pick_xi(pool, force=p) if p["slot"] else None
                gap = (forced[0] - tot) if forced else None
                cpp = p["value"] / p["score"] if p["score"] > 0.05 \
                    else float("inf")
                if p["status"] in ("injured", "suspended", "unavailable"):
                    why = p["status"]
                elif p["status"] == "doubt":
                    why = "doubtful"
                elif p["slot"] and rank.get(id(p), 0) >= MAX_SLOT[p["slot"]]:
                    nth = rank[id(p)] + 1
                    sfx = ("th" if nth % 100 in (11, 12, 13)
                           else {1: "st", 2: "nd", 3: "rd"}.get(nth % 10, "th"))
                    why = (f"{nth}{sfx} {p['slot']} — only "
                           f"{MAX_SLOT[p['slot']]} can ever play")
                elif p["delta_pct"] >= MOVER_PCT:
                    why = "rising — sell into strength"
                elif p["pos"] == "entrenador":
                    why = "coach slot"
                elif gap is not None and gap > -0.15:
                    why = "as good as the man ahead"
                else:
                    why = "outscored"
                rows.append((cpp, p, gap, why))
            rows.sort(key=lambda t: t[0], reverse=True)
            out += ["**Gap** is what the XI loses per jornada if he has to "
                    "play, after re-picking the formation. **€/pt** is value "
                    "per expected point: the sell shortlist, worst first.", "",
                    "| Player | Pos | Value | xPts/j | Gap | €/pt | Why |",
                    "|---|---|--:|--:|--:|--:|---|"]
            for cpp, p, gap, why in rows:
                out.append(
                    f"| {p['name']} | {p['pos'][:3]} | {eur(p['value'])} | "
                    f"{p['score']:.1f} | "
                    f"{'—' if gap is None else format(gap, '+.1f')} | "
                    f"{'—' if cpp == float('inf') else eur(cpp)} | {why} |")
            out += ["", "_%s Who is short in this position, and who can "
                        "still afford you, is in `reports/rivals.md`._" % (
                            "Selling to the app pays the value give or take "
                            "%.0f%%: the %d priced sales in the ledger went "
                            "%s, so read every value above as that band, not "
                            "as a number." % (app_prem.swing(), app_prem.n,
                                              app_prem.label())
                            if app_prem and app_prem.n >= 3 else
                            "A sale lands above or below value depending on "
                            "who bids."), ""]

        log_squad(observed, players, chosen, (d, m, f), tot, deadline, obs_dt)

    # --- your movers ------------------------------------------------------
    movers = sorted((p for p in players if abs(p["delta_pct"]) >= MOVER_PCT),
                    key=lambda p: p["delta_pct"], reverse=True)
    out += [f"## Your movers (24h, over {MOVER_PCT:.0f}%)", ""]
    if not movers:
        out += ["_Nothing in your squad moved much._", ""]
    else:
        out += ["| Player | Value | 24h | % |", "|---|--:|--:|--:|"]
        for p in movers:
            out.append(f"| {p['name']} | {eur(p['value'])} | "
                       f"{eur(p['delta_1d'])} | {p['delta_pct']:+.2f}% |")
        out.append("")

    out += [
        "## Notes",
        "",
        f"_{len(market)} players tracked, {len(sc.start_pct)} with a "
        "probable-XI reading._",
        "",
        f"_xPts/j — expected points per jornada = shrunk pts/match "
        f"(K={shrink_k:.0f}"
        + (f", {hist_label}" if hist_label else ", **no points baseline**")
        + ") × P(start), from `ffcore/score.py` — the same scorer rivals.py "
          "uses. Injured, suspended and unavailable score zero; a doubt is "
          "halved._",
        "",
        f"_Generated {now:%Y-%m-%d %H:%M} UTC._",
    ]

    write_lines(REPORTS / "latest.md", out)
    write_lines(HISTORY / f"{observed[:10]}.md", out)


def _selftest() -> None:
    """The cells that carry a judgement. main() needs a repo to run against;
    these do not, so they are the part CI can hold still."""
    def pl(pct=None, on_page=True, used=None, ppm=4.0, assumed=False):
        return {"pct": pct, "on_page": on_page, "ppm": ppm, "assumed": assumed,
                "pct_used": pct if used is None else used}

    # --- AF's two shapes, kept in their own units ---
    assert af_cell(None) == "—"                     # not joined at all
    assert af_cell({"role": "starter", "start_pct": ""}) == "titular"
    # A named starter is NOT rendered as a percentage: doing so would mean
    # inventing the yes→probability constant, and nothing exists to fit it.
    assert "%" not in af_cell({"role": "starter", "start_pct": ""})
    assert af_cell({"role": "starter", "start_pct": "100.0"}) == "100%"
    assert af_cell({"role": "doubt", "start_pct": "66.7"}) == "67%"
    assert af_cell({"role": "doubt", "start_pct": ""}) == "?"

    # --- FF's cell, and the marks that say "assumed", not "read" ---
    assert pct_cell(pl(pct=80.0)) == "80%"
    assert pct_cell(pl(on_page=True)).startswith("~")
    assert pct_cell(pl(on_page=False)).startswith("!")
    assert ppm_cell(pl(ppm=3.14)) == "3.1"
    assert ppm_cell(pl(ppm=3.14, assumed=True)) == "~3.1"

    # --- the disagreement that changes a decision, and the ones that don't ---
    starter = {"role": "starter", "start_pct": ""}
    out = {"role": "doubt", "start_pct": "33.3"}
    assert disagrees(pl(pct=90.0), starter, 60.0) == ""    # both say yes
    assert disagrees(pl(pct=10.0), out, 60.0) == ""        # both say no
    # FF has him starting, AF has him a third likely: that is the split.
    assert "33%" in disagrees(pl(pct=90.0), out, 60.0)
    assert "futbolfantasy 90%" in disagrees(pl(pct=90.0), out, 60.0)
    # And the reverse reads the other way round, AF first.
    rev = disagrees(pl(pct=10.0), starter, 60.0)
    assert rev.startswith(SECOND_SOURCE) and "titular" in rev
    # No second-source row is not a disagreement — it is silence.
    assert disagrees(pl(pct=90.0), None, 60.0) == ""

    # --- names ---
    # A particle stays lowercase inside a name, but not as its first word.
    assert title_name("nico van gaal") == "Nico van Gaal"
    assert title_name("de la fuente") == "De La Fuente"
    assert title_name("Vini Jr.") == "Vini Jr."      # already cased

    print("report self-test OK (22 cases)")


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        _selftest()
        raise SystemExit(0)
    main()
